#define SDL_MAIN_USE_CALLBACKS 1  /* use the callbacks instead of main() */

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_image/SDL_image.h>
#include <stdio.h>
#include "WzGuiCore.h"
#include "WzLayout_ispc.h"  // generated by: ispc WzLayout.ispc --target=avx2-i32x8 --header-outfile=WzLayout_ispc.h
#define _USE_MATH_DEFINES
#include <math.h>

#define CONCAT(a, b) a##b
#define ITEM(name, num) CONCAT(name, num),

// These must be hard-coded because the preprocessor can't do "offset + 1"
#define GEN_2(n, o0, o1)      ITEM(n, o0) ITEM(n, o1)
#define GEN_4(n, o0, o1, o2, o3) GEN_2(n, o0, o1) GEN_2(n, o2, o3)

// To avoid writing 512 arguments, we use a slightly different "Nested" approach:
#define B000(n, p) ITEM(n, p##0) ITEM(n, p##1) ITEM(n, p##2) ITEM(n, p##3) ITEM(n, p##4) ITEM(n, p##5) ITEM(n, p##6) ITEM(n, p##7)
#define B00(n, p)  B000(n, p##0) B000(n, p##1) B000(n, p##2) B000(n, p##3) B000(n, p##4) B000(n, p##5) B000(n, p##6) B000(n, p##7)

// This will generate items 000 through 511 (formatted as 3 digits to avoid math)
#define GEN_512_SAFE(n) \
    B00(n, 0) B00(n, 1) B00(n, 2) B00(n, 3) B00(n, 4) B00(n, 5) B00(n, 6) B00(n, 7)

enum
{
	WIDGET_INPUT_BOX1,
	WIDGET_INPUT_BOX2,
	WIDGET_INPUT_BOX3,
	GEN_512_SAFE(WIDGET_LABEL_LIST)
};


#define STB_TEXTEDIT_IMPLEMENTATION
#include "stb_textedit.h"

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

static void wz_layout_ispc_test(void);
static void wz_layout_draw_test(SDL_Renderer* renderer, WzDrawCommandBuffer* out);
static void WSDL_RenderCommandBuffer(SDL_Renderer* renderer, WzDrawCommandBuffer* buf);

#define MAX_NUM_EVENTS 128
unsigned events_count;
WzEvent events[MAX_NUM_EVENTS];

static unsigned short sdl_keymod_to_wz(SDL_Keymod sdl_mod)
{
	unsigned short wz_mod = WZ_KMOD_NONE;

	if (sdl_mod & SDL_KMOD_LSHIFT) wz_mod |= WZ_KMOD_LSHIFT;
	if (sdl_mod & SDL_KMOD_RSHIFT) wz_mod |= WZ_KMOD_RSHIFT;
	if (sdl_mod & SDL_KMOD_LCTRL)  wz_mod |= WZ_KMOD_LCTRL;
	if (sdl_mod & SDL_KMOD_RCTRL)  wz_mod |= WZ_KMOD_RCTRL;
	if (sdl_mod & SDL_KMOD_LALT)   wz_mod |= WZ_KMOD_LALT;
	if (sdl_mod & SDL_KMOD_RALT)   wz_mod |= WZ_KMOD_RALT;
	if (sdl_mod & SDL_KMOD_LGUI)   wz_mod |= WZ_KMOD_LGUI;
	if (sdl_mod & SDL_KMOD_RGUI)   wz_mod |= WZ_KMOD_RGUI;

	return wz_mod;
}

// Convert SDL3 scancode + modifiers to WZ keycode
// Returns 0-127 for ASCII characters, 128+ for special keys
WZ_Keycode wz_sdl_scancode_to_keycode(SDL_Scancode scancode, SDL_Keymod modifiers)
{
	bool shift = (modifiers & (SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT)) != 0;
	bool caps = (modifiers & SDL_KMOD_CAPS) != 0;

	// Letters A-Z
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		char base = 'a' + (scancode - SDL_SCANCODE_A);
		// Caps lock XOR shift gives uppercase
		if (caps != shift) {
			return base - 32; // Uppercase ASCII
		}
		return base; // Lowercase ASCII
	}

	// Numbers 1-9, 0
	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		if (shift) {
			const char symbols[] = "!@#$%^&*(";
			return symbols[scancode - SDL_SCANCODE_1];
		}
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) {
		return shift ? ')' : '0';
	}

	// Punctuation and special keys (ASCII range)
	switch (scancode) {
	case SDL_SCANCODE_SPACE:      return ' ';
	case SDL_SCANCODE_RETURN:     return '\n';
	case SDL_SCANCODE_ESCAPE:     return 27;
	case SDL_SCANCODE_BACKSPACE:  return '\b';
	case SDL_SCANCODE_TAB:        return '\t';

	case SDL_SCANCODE_MINUS:      return shift ? '_' : '-';
	case SDL_SCANCODE_EQUALS:     return shift ? '+' : '=';
	case SDL_SCANCODE_LEFTBRACKET:  return shift ? '{' : '[';
	case SDL_SCANCODE_RIGHTBRACKET: return shift ? '}' : ']';
	case SDL_SCANCODE_BACKSLASH:    return shift ? '|' : '\\';
	case SDL_SCANCODE_SEMICOLON:    return shift ? ':' : ';';
	case SDL_SCANCODE_APOSTROPHE:   return shift ? '"' : '\'';
	case SDL_SCANCODE_GRAVE:        return shift ? '~' : '`';
	case SDL_SCANCODE_COMMA:        return shift ? '<' : ',';
	case SDL_SCANCODE_PERIOD:       return shift ? '>' : '.';
	case SDL_SCANCODE_SLASH:        return shift ? '?' : '/';
	}

	// Extended keys (128+)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK:     return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1:           return WZ_KEY_F1;
	case SDL_SCANCODE_F2:           return WZ_KEY_F2;
	case SDL_SCANCODE_F3:           return WZ_KEY_F3;
	case SDL_SCANCODE_F4:           return WZ_KEY_F4;
	case SDL_SCANCODE_F5:           return WZ_KEY_F5;
	case SDL_SCANCODE_F6:           return WZ_KEY_F6;
	case SDL_SCANCODE_F7:           return WZ_KEY_F7;
	case SDL_SCANCODE_F8:           return WZ_KEY_F8;
	case SDL_SCANCODE_F9:           return WZ_KEY_F9;
	case SDL_SCANCODE_F10:          return WZ_KEY_F10;
	case SDL_SCANCODE_F11:          return WZ_KEY_F11;
	case SDL_SCANCODE_F12:          return WZ_KEY_F12;

	case SDL_SCANCODE_PRINTSCREEN:  return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK:   return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE:        return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT:       return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME:         return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP:       return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE:       return WZ_KEY_DELETE;
	case SDL_SCANCODE_END:          return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN:     return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT:        return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT:         return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN:         return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP:           return WZ_KEY_UP;

	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE:    return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY:  return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS:     return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS:      return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER:     return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1:         return (modifiers & SDL_KMOD_NUM) ? '1' : WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2:         return (modifiers & SDL_KMOD_NUM) ? '2' : WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3:         return (modifiers & SDL_KMOD_NUM) ? '3' : WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4:         return (modifiers & SDL_KMOD_NUM) ? '4' : WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5:         return (modifiers & SDL_KMOD_NUM) ? '5' : WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6:         return (modifiers & SDL_KMOD_NUM) ? '6' : WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7:         return (modifiers & SDL_KMOD_NUM) ? '7' : WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8:         return (modifiers & SDL_KMOD_NUM) ? '8' : WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9:         return (modifiers & SDL_KMOD_NUM) ? '9' : WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0:         return (modifiers & SDL_KMOD_NUM) ? '0' : WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD:    return (modifiers & SDL_KMOD_NUM) ? '.' : WZ_KEY_KP_PERIOD;

	case SDL_SCANCODE_APPLICATION:  return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER:        return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS:    return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13:          return WZ_KEY_F13;
	case SDL_SCANCODE_F14:          return WZ_KEY_F14;
	case SDL_SCANCODE_F15:          return WZ_KEY_F15;
	case SDL_SCANCODE_F16:          return WZ_KEY_F16;
	case SDL_SCANCODE_F17:          return WZ_KEY_F17;
	case SDL_SCANCODE_F18:          return WZ_KEY_F18;
	case SDL_SCANCODE_F19:          return WZ_KEY_F19;
	case SDL_SCANCODE_F20:          return WZ_KEY_F20;
	case SDL_SCANCODE_F21:          return WZ_KEY_F21;
	case SDL_SCANCODE_F22:          return WZ_KEY_F22;
	case SDL_SCANCODE_F23:          return WZ_KEY_F23;
	case SDL_SCANCODE_F24:          return WZ_KEY_F24;

	case SDL_SCANCODE_EXECUTE:      return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP:         return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU:         return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT:       return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP:         return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN:        return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO:         return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT:          return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY:         return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE:        return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND:         return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE:         return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP:     return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN:   return WZ_KEY_VOLUMEDOWN;

	case SDL_SCANCODE_LCTRL:        return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT:       return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT:         return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI:         return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL:        return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT:       return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT:         return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI:         return WZ_KEY_RGUI;

	case SDL_SCANCODE_MODE:         return WZ_KEY_MODE;

	default:
		return WZ_KEY_UNKNOWN;
	}
}

// Helper: Check if keycode is printable ASCII
bool wz_keycode_is_printable(WZ_Keycode keycode)
{
	return keycode >= 32 && keycode <= 126;
}

// Helper: Check if keycode is ASCII (printable or control)
bool wz_keycode_is_ascii(WZ_Keycode keycode)
{
	return keycode >= 0 && keycode < 128;
}

// Helper: Check if keycode is extended (special key)
bool wz_keycode_is_extended(WZ_Keycode keycode)
{
	return keycode >= 128 && keycode < WZ_KEY_COUNT;
}

void render_text(SDL_Renderer* renderer, stbtt_fontinfo* font,
	const char* text, float x, float y, float font_size, unsigned len)
{
	float scale = stbtt_ScaleForPixelHeight(font, font_size);
	int ascent, descent, lineGap;
	stbtt_GetFontVMetrics(font, &ascent, &descent, &lineGap);
	int baseline = (int)(ascent * scale);
	float current_x = x;  // Changed to float
	int current_y = y;

	for (int i = 0; i < len; i++)
	{
		// Handle newlines
		if (text[i] == '\n') {
			current_x = x;
			current_y += (int)((ascent - descent + lineGap) * scale);
			continue;
		}
		// Get glyph bitmap
		int width, height, xoff, yoff;
		unsigned char* bitmap = stbtt_GetCodepointBitmap(font, 0, scale,
			text[i], &width, &height,
			&xoff, &yoff);
		// Get horizontal advance for this character
		int advance, lsb;
		stbtt_GetCodepointHMetrics(font, text[i], &advance, &lsb);
		if (bitmap)
		{
			// Render the bitmap pixel by pixel
			for (int row = 0; row < height; row++) {
				for (int col = 0; col < width; col++) {
					unsigned char pixel = bitmap[row * width + col];
					if (pixel > 0) {
						// Set color based on alpha value
						SDL_SetRenderDrawColor(renderer, 0, 0, 0, pixel);
						SDL_RenderPoint(renderer,
							(int)current_x + xoff + col,  // Cast to int only when rendering
							current_y + baseline + yoff + row);
					}
				}
			}
			stbtt_FreeBitmap(bitmap, NULL);
		}
		// Move to next character position - keep as float!
		current_x += advance * scale;  // Removed (int) cast
		// Apply kerning if there's a next character
		if (i + 1 < len)  // Also fixed this from text[i+1]
		{
			int kern = stbtt_GetCodepointKernAdvance(font, text[i], text[i + 1]);
			current_x += kern * scale;  // Removed (int) cast
		}
	}
}

typedef struct Wsdl
{
	WzKeyboard keyboard;
} Wsdl;

Wsdl wsdl;

typedef struct
{
	SDL_Window* window;
	SDL_Renderer* renderer;
	TTF_TextEngine* text_engine;
	WzGui gui;
} WSDL_Context;

WSDL_Context main_window;
WSDL_Context gui_window;

#define WZ_MAX_FONTS 16
stbtt_fontinfo fonts[WZ_MAX_FONTS];
float font_heights[WZ_MAX_FONTS];
static int fonts_count = 0;
SDL_Texture* x_icon_texture;


// Color component extraction macros (for RGBA format: 0xRRGGBBAA)
#define WZ_COLOR_R(c) (((c) >> 24) & 0xFF)
#define WZ_COLOR_G(c) (((c) >> 16) & 0xFF)
#define WZ_COLOR_B(c) (((c) >> 8) & 0xFF)
#define WZ_COLOR_A(c) ((c) & 0xFF)
#define WZ_RGBA(r,g,b,a) (((unsigned)(r)<<24)|((unsigned)(g)<<16)|((unsigned)(b)<<8)|(unsigned)(a))

static WzDrawCommandBuffer ispc_cmds;

static void wz_push_filled_rect(WzDrawCommandBuffer* buf, float x, float y, float w, float h, unsigned color)
{
	if (!buf || buf->count >= MAX_NUM_DRAW_COMMANDS - 1) return;
	WzDrawCommand* cmd = &buf->commands[buf->count++];
	cmd->type = DrawCommandType_Rect;
	cmd->x = x; cmd->y = y; cmd->w = w; cmd->h = h; cmd->color = color;
}

static void wz_ispc_push_rect(WzDrawCommandBuffer* buf, const struct WzSlot* slot, int lane, unsigned color)
{
	wz_push_filled_rect(buf, slot->abs_x[lane], slot->abs_y[lane], slot->abs_width[lane], slot->abs_height[lane], color);
}

//#define assert(x) void(x)

#define MAX_NUM_TEXTURES_IN_ANIMATION 128

typedef struct Animation
{
	SDL_Texture* textures[MAX_NUM_TEXTURES_IN_ANIMATION];
	unsigned textures_count;
	unsigned w, h;
} Animation;

typedef struct WzWidgetPersistentData
{
	WzWidget widget;
	float transform_x, transform_y;
	float scale_x, scale_y;
	float rotation;

	Animation animation;
	unsigned current_animation_frame;
} WzWidgetPersistentData;

#define MAX_NUM_IMAGE_WIDGETS 32
WzWidgetPersistentData image_widgets[MAX_NUM_IMAGE_WIDGETS];
unsigned image_widgets_count;

WzGui gui;

WzTexture texture;

#define MAX_NUM_RENDERERS 16
#define MAX_NUM_WINDOWS 16


WzState left_mouse;

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 540

bool error;



bool load_animation(SDL_Renderer* renderer, Animation* animation, const char* path)
{
	bool success = true;
	IMG_Animation* anim = IMG_LoadAnimation(path);

	if (!anim)
	{
		return false;
	}

	if (anim->count == MAX_NUM_TEXTURES_IN_ANIMATION)
	{
		SDL_SetError("Loaded to many gifs");
		return false;
	}

	*animation = (Animation){ .textures_count = anim->count, .w = anim->w, .h = anim->h };
	for (int i = 0; i < anim->count; i++)
	{
		animation->textures[i] = SDL_CreateTextureFromSurface(renderer, anim->frames[i]);
		if (!animation->textures[i])
		{
			return false;
		}
	}
}

static void WSDL_RenderCommandBuffer(SDL_Renderer* renderer, WzDrawCommandBuffer* buf)
{
	for (int i = 0; i < buf->count; ++i)
	{
		WzDrawCommand command = buf->commands[i];
		if (command.type == DrawCommandType_Rect)
		{
			SDL_SetRenderDrawColor(renderer,
				WZ_COLOR_R(command.color), WZ_COLOR_G(command.color),
				WZ_COLOR_B(command.color), WZ_COLOR_A(command.color));
			SDL_FRect rect = { command.x, command.y, command.w, command.h };
			SDL_RenderFillRect(renderer, &rect);
		}
	}
}

static void WSDL_WzBeginWidgets(WSDL_Context* context)
{

	Uint32 flags = SDL_GetWindowFlags(context->window);
	float mouse_x = 0, mouse_y = 0;
	if (flags & SDL_WINDOW_MOUSE_FOCUS)
	{
		SDL_GetMouseState(&mouse_x, &mouse_y);
	}

	context->gui.mouse_pos.x = mouse_x;
	context->gui.mouse_pos.y = mouse_y;
#if 0

	// Mouse Input
	{
		float mx, my;
		Uint32 mflags = SDL_GetMouseState(&mx, &my);
		printf("%u\n", mflags);

		if (left_mouse == WZ_ACTIVATING)
		{
			left_mouse = WZ_ACTIVE;
		}
		else if (left_mouse == WZ_DEACTIVATING)
		{
			left_mouse = WZ_INACTIVE;
		}

		if (mflags & SDL_BUTTON_LMASK)
		{
			if (left_mouse == WZ_INACTIVE)
			{
				left_mouse = WZ_ACTIVATING;
			}
		}
		else
		{
			if (left_mouse == WZ_ACTIVE)
			{
				left_mouse = WZ_DEACTIVATING;
			}
		}
	}
#endif
	wz_begin(WINDOW_WIDTH, WINDOW_HEIGHT,
		events, events_count, true);
}

void WSDL_WzEnd(WSDL_Context* context)
{
	wz_end();

	// Draw
	SDL_Renderer* renderer = context->renderer;

	WzDrawCommandBuffer* buffer = &context->gui.commands_buffer;

	for (int i = 0; i < buffer->count; ++i)
	{
		WzDrawCommand command = buffer->commands[i];

		if (command.type == DrawCommandType_Rect)
		{
			SDL_SetRenderDrawColor(renderer,
				WZ_COLOR_R(command.color), WZ_COLOR_G(command.color),
				WZ_COLOR_B(command.color), WZ_COLOR_A(command.color));
			SDL_FRect rect = { command.x, command.y, command.w, command.h };
			SDL_RenderFillRect(renderer, &rect);
		}
		else if (command.type == DrawCommandType_Texture)
		{
			SDL_SetTextureBlendMode(command.texture.data, SDL_BLENDMODE_BLEND);

			SDL_FRect src = { (float)command.src_rect.x, (float)command.src_rect.y, (float)command.src_rect.w, (float)command.src_rect.h };
			SDL_FRect dest = { command.x, command.y, command.w, command.h };
			SDL_RenderTextureRotated(renderer, command.texture.data,
				&src, &dest, command.rotation_angle, 0, 0);
		}
		else if (command.type == WZ_DRAW_COMMAND_TYPE_TEXT)
		{
			render_text(renderer, &fonts[command.font_id],
				command.str.str, command.x, command.y, font_heights[command.font_id], command.str.len);
		}
		else if (command.type == DrawCommandType_Line)
		{
			SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);

			SDL_SetRenderDrawColor(renderer, WZ_COLOR_R(command.color), WZ_COLOR_G(command.color), WZ_COLOR_B(command.color), 255);
			SDL_RenderLine(renderer, command.line.x0, command.line.y0, command.line.x1, command.line.y1);
		}
		else if (command.type == DrawCommandType_LineDotted)
		{
			SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);

			// Bresenheim
			int dx = abs(command.line.x1 - command.line.x0);
			int sx = command.line.x0 < command.line.x1 ? 1 : -1;
			int dy = -abs(command.line.y1 - command.line.y0);
			int sy = command.line.y0 < command.line.y1 ? 1 : -1;
			int error = dx + dy;
			int x0 = command.line.x0;
			int y0 = command.line.y0;
			int x1 = command.line.x1;
			int y1 = command.line.y1;

			bool draw = true;

			while (1)
			{
				if (draw)
				{
					SDL_RenderPoint(renderer, x0, y0);
				}
				draw = !draw;

				int e2 = 2 * error;

				if (e2 >= dy)
				{
					if (x0 == x1)
					{
						break;
					}

					error = error + dy;
					x0 = x0 + sx;
				}

				if (e2 <= dx)
				{
					if (y0 == y1)
					{
						break;
					}

					error = error + dx;
					y0 = y0 + sy;
				}
			}
		}
		else if (command.type == DrawCommandType_VerticalLine)
		{
			SDL_SetRenderDrawColor(renderer, 125, 125, 125, 255);

			int x = command.x;
			int y = command.y;
			int h = command.h;
			for (int i = y; i < y + h; ++i)
			{
				if (i % 2 == 1) continue;
				SDL_RenderPoint(renderer, (float)x, (float)i);
			}
		}
		else if (command.type == DrawCommandType_HorizontalLine)
		{
			SDL_SetRenderDrawColor(renderer, 125, 125, 125, 255);
			int x = command.x;
			int y = command.y;
			int w = command.w;
			for (int i = x; i < x + w; ++i)
			{
				if (i % 2 == 1) continue;
				SDL_RenderPoint(renderer, (float)i, (float)y);
			}
		}
		else if (command.type == DrawCommandType_Clip)
		{
#if 1
			SDL_Rect rect = { (int)command.x, (int)command.y, (int)command.w, (int)command.h };
			SDL_SetRenderClipRect(renderer, &rect);
#else
			SDL_SetRenderDrawColor(renderer,
				255, 0, 0, 125);
			SDL_FRect rect = { command.x, command.y, command.w, command.h };
			SDL_RenderFillRect(renderer, &rect);
#endif
		}
		else if (command.type == DrawCommandType_StopClip)
		{
			SDL_SetRenderClipRect(renderer, 0);
		}
	}

	SDL_SetRenderClipRect(renderer, 0);
}

void WSDL_HandleInput()
{
	for (unsigned i = 0; i < 512; ++i)
	{
		if (wsdl.keyboard.keys[i] == WZ_ACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_ACTIVE;
		}
		if (wsdl.keyboard.keys[i] == WZ_DEACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_INACTIVE;
		}
	}

	int num_keys = 0;
	bool* keys = SDL_GetKeyboardState(&num_keys);
	for (unsigned i = 0; i < num_keys; ++i)
	{
		WZ_Keycode keycode = wz_sdl_scancode_to_keycode(i, 0);
		{
			if (keys[i])
			{
				if (wsdl.keyboard.keys[keycode] == WZ_INACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_ACTIVATING;
				}
			}
			else
			{
				if (wsdl.keyboard.keys[keycode] == WZ_ACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_DEACTIVATING;
				}
			}
		}
	}

}

static int WSDL_TranslateToWzKeycodes(SDL_Scancode scancode) {
	// Handle ASCII range (a-z, 0-9, punctuation, etc.)
	// SDL scancodes for letters are offset from ASCII
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		return 'a' + (scancode - SDL_SCANCODE_A);  // Map to lowercase ASCII
	}

	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) return '0';


	// Special ASCII characters
	switch (scancode) {
	case SDL_SCANCODE_SPACE: return ' ';
	case SDL_SCANCODE_RETURN: return '\n';
	case SDL_SCANCODE_TAB: return '\t';
	case SDL_SCANCODE_BACKSPACE: return '\b';
	case SDL_SCANCODE_ESCAPE: return 27;  // ESC

		// Punctuation (you may need to adjust these based on your keyboard layout)
	case SDL_SCANCODE_MINUS: return '-';
	case SDL_SCANCODE_EQUALS: return '=';
	case SDL_SCANCODE_LEFTBRACKET: return '[';
	case SDL_SCANCODE_RIGHTBRACKET: return ']';
	case SDL_SCANCODE_BACKSLASH: return '\\';
	case SDL_SCANCODE_SEMICOLON: return ';';
	case SDL_SCANCODE_APOSTROPHE: return '\'';
	case SDL_SCANCODE_GRAVE: return '`';
	case SDL_SCANCODE_COMMA: return ',';
	case SDL_SCANCODE_PERIOD: return '.';
	case SDL_SCANCODE_SLASH: return '/';
	}

	// Extended keys (>= 128)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK: return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1: return WZ_KEY_F1;
	case SDL_SCANCODE_F2: return WZ_KEY_F2;
	case SDL_SCANCODE_F3: return WZ_KEY_F3;
	case SDL_SCANCODE_F4: return WZ_KEY_F4;
	case SDL_SCANCODE_F5: return WZ_KEY_F5;
	case SDL_SCANCODE_F6: return WZ_KEY_F6;
	case SDL_SCANCODE_F7: return WZ_KEY_F7;
	case SDL_SCANCODE_F8: return WZ_KEY_F8;
	case SDL_SCANCODE_F9: return WZ_KEY_F9;
	case SDL_SCANCODE_F10: return WZ_KEY_F10;
	case SDL_SCANCODE_F11: return WZ_KEY_F11;
	case SDL_SCANCODE_F12: return WZ_KEY_F12;
	case SDL_SCANCODE_PRINTSCREEN: return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK: return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE: return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT: return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME: return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP: return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE: return WZ_KEY_DELETE;
	case SDL_SCANCODE_END: return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN: return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT: return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT: return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN: return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP: return WZ_KEY_UP;
	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE: return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY: return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS: return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS: return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER: return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1: return WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2: return WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3: return WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4: return WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5: return WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6: return WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7: return WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8: return WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9: return WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0: return WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD: return WZ_KEY_KP_PERIOD;
	case SDL_SCANCODE_APPLICATION: return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER: return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS: return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13: return WZ_KEY_F13;
	case SDL_SCANCODE_F14: return WZ_KEY_F14;
	case SDL_SCANCODE_F15: return WZ_KEY_F15;
	case SDL_SCANCODE_F16: return WZ_KEY_F16;
	case SDL_SCANCODE_F17: return WZ_KEY_F17;
	case SDL_SCANCODE_F18: return WZ_KEY_F18;
	case SDL_SCANCODE_F19: return WZ_KEY_F19;
	case SDL_SCANCODE_F20: return WZ_KEY_F20;
	case SDL_SCANCODE_F21: return WZ_KEY_F21;
	case SDL_SCANCODE_F22: return WZ_KEY_F22;
	case SDL_SCANCODE_F23: return WZ_KEY_F23;
	case SDL_SCANCODE_F24: return WZ_KEY_F24;
	case SDL_SCANCODE_EXECUTE: return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP: return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU: return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT: return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP: return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN: return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO: return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT: return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY: return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE: return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND: return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE: return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP: return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN: return WZ_KEY_VOLUMEDOWN;
	case SDL_SCANCODE_LCTRL: return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT: return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT: return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI: return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL: return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT: return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT: return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI: return WZ_KEY_RGUI;
	case SDL_SCANCODE_MODE: return WZ_KEY_MODE;

	default: return WZ_KEY_UNKNOWN;
	}
}

SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
	WzEvent wz_event = { 0 };

	switch (event->type) {
	case SDL_EVENT_KEY_DOWN: {
		unsigned wz_key = (unsigned)wz_sdl_scancode_to_keycode(event->key.scancode, event->key.mod);
		if (wz_key != WZ_KEY_UNKNOWN) {
			bool is_repeat = (event->key.repeat != 0);
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.key = wz_key,
				.down = true,
				.repeat = is_repeat,
				.mod = sdl_keymod_to_wz(event->key.mod),
			};
		}
		break;
	}

	case SDL_EVENT_KEY_UP: {
		int wz_key = WSDL_TranslateToWzKeycodes(event->key.scancode);
		if (wz_key != WZ_KEY_UNKNOWN) {
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.mod = sdl_keymod_to_wz(event->key.mod),
				.key = wz_key,
			};
		}
		break;
	}

						 // Mouse button events
	case SDL_EVENT_MOUSE_BUTTON_DOWN: {
		wz_input_mouse_button_event(
			event->button.button,
			true,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.down = true,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};
		break;
	}

	case SDL_EVENT_MOUSE_BUTTON_UP: {
		wz_input_mouse_button_event(
			event->button.button,
			false,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};

		break;
	}

	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}

	if (wz_event.type)
	{
		events[events_count++] = wz_event;
		assert(events_count < MAX_NUM_EVENTS);
	}

	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void* appstate)
{
	wz_gui_deinit(&gui);
}

SDL_EnumerationResult SDLCALL onFile(void* userdata, const char* dirname, const char* filename)
{
#if 0
	char path[512];
	sprintf(path, "%s%s", dirname, filename);

	assert(image_widgets_count < MAX_NUM_IMAGE_WIDGETS - 1);
	load_animation(renderer, &image_widgets[image_widgets_count].animation, path);
	image_widgets[image_widgets_count].scale_x = 1;
	image_widgets[image_widgets_count].scale_y = 1;
	image_widgets_count++;
#endif

	return SDL_ENUM_CONTINUE;
}

void load_animations()
{
	bool result = SDL_EnumerateDirectory("Gifs", onFile, 0);
	if (!result)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}
}

void WSDL_ContextCreate(WSDL_Context* context, unsigned window_width, unsigned window_height)
{
	bool success = true;
	SDL_Renderer* renderer;
	SDL_Window* window;
	TTF_TextEngine* text_engine;

	success &= SDL_SetHint(SDL_HINT_RENDER_DRIVER, "direct3d");

	success &= SDL_CreateWindowAndRenderer("my window", window_width, window_height,
		SDL_WINDOW_RESIZABLE, &window, &renderer);

	success &= SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

	text_engine = TTF_CreateRendererTextEngine(renderer);
	success &= (bool)text_engine;

	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);
	}

	context->renderer = renderer;
	context->window = window;
	context->text_engine = text_engine;
}

SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
	bool success = false;

	WSDL_ContextCreate(&gui_window, WINDOW_WIDTH, WINDOW_HEIGHT);

	// stb fonts
	{
		// Font 0: Arial 18px (default)
		size_t file_size;
		char* data = SDL_LoadFile("C:\\Windows\\Fonts\\Arial.ttf", &file_size);
		if (!data) {
			SDL_Log("Failed to load font: %s", SDL_GetError());
			SDL_Quit();
			return 1;
		}
		stbtt_InitFont(&fonts[0], data, 0);
		font_heights[0] = 18;
		fonts_count = 1;

		// Font 1: Arial 28px
		char* data2 = SDL_LoadFile("C:\\Windows\\Fonts\\Arial.ttf", &file_size);
		if (data2) {
			stbtt_InitFont(&fonts[1], data2, 0);
			font_heights[1] = 28;
			fonts_count = 2;
		}
	}

	// X icon
	{
		// TODO: Remove width and height fields of wz texture
		SDL_Surface* surface = SDL_CreateSurfaceFrom(16, 16, SDL_PIXELFORMAT_RGBA8888, wz_x_icon, 16 * 4);
		success |= (bool)surface;
		gui.x_icon = (WzTexture){ .w = surface->w, .h = surface->h, .data = SDL_CreateTextureFromSurface(gui_window.renderer, surface) };
	}


	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}

	load_animations();

	//wz_layout_ispc_test();

	return SDL_APP_CONTINUE;
}

void get_string_size(char* str, unsigned start, unsigned end, unsigned font_id, float* w, float* h)
{
	stbtt_fontinfo* f = &fonts[font_id];
	float fh = font_heights[font_id];
	float scale = stbtt_ScaleForPixelHeight(f, fh);
	float width = 0;
	for (int i = start; i < end; i++)
	{
		int advance, lsb;
		stbtt_GetCodepointHMetrics(f, str[i], &advance, &lsb);
		width += advance * scale;
		if (i + 1 < end) {
			int kern = stbtt_GetCodepointKernAdvance(f, str[i], str[i + 1]);
			width += kern * scale;
		}
	}
	*w = width;
	*h = fh;
}


void WSDL_WindowContextBegin(WSDL_Context* context)
{
	bool success = true;
	success &= SDL_SetRenderDrawColor(context->renderer, 0x20, 0x8c, 0x71, 255);
	success &= SDL_RenderClear(context->renderer);
}

WzWidget WSDL_WzBegin(WSDL_Context* context)
{
	int window_width, window_height;
	SDL_GetWindowSize(context->window, &window_width, &window_height);

	WSDL_WindowContextBegin(&gui_window);
}

bool WSDL_IsInteracting(char k)
{
	bool result = wsdl.keyboard.keys[k] == WZ_ACTIVATING || wsdl.keyboard.keys[k] == WZ_ACTIVE;

	return result;
}

SDL_AppResult SDL_AppIterate(void* appstate)
{
	unsigned time_beginning = SDL_GetTicks();

	bool success = true;

	ispc_cmds.count = 0;

	WSDL_WzBegin(&gui_window);
	//wz_layout_draw_test(gui_window.renderer, &ispc_cmds);
	wz_set_gui(&gui_window.gui);
	wz_set_string_size_callback(get_string_size);

	gui_window.gui.ticks_in_ns = SDL_GetTicksNS;
	gui_window.gui.ticks_in_ms = SDL_GetTicks;

	WSDL_WzBeginWidgets(&gui_window);

	WzWidget ib_window = wz_vbox((WzWidget) { 0 });
	wz_widget_set_size(ib_window, 300, 30);
	wz_widget_set_border(ib_window, WZ_BORDER_TYPE_NONE);

	// Widgets declarations
	gui_window.gui.pasted_text = SDL_GetClipboardText();
	wz_widget_set_size(ib_window, 300, 60);
	static WzInputState state, state2, s;
	if (1)
	{
#if 0
		WzWidget input_box = wz_text_box(ib_window, &state, WZ_INPUT_NONE, NULL, NULL, NULL);
		WzWidget input_box2 = wz_text_box(ib_window, &s, WZ_INPUT_NONE, NULL, NULL, NULL);
		WzWidget input_box3 = wz_text_box(ib_window, &state2, WZ_INPUT_NONE, NULL, NULL, NULL);
		wz_widget_set_font(input_box2, 1);

		static float pos;
		wz_slider(ib_window, 200, &pos);
#endif
		//bool b;
		//wz_command_button(wz_str_create("wow"), &b, ib_window);

		static unsigned selected_text;
		WzStr strs[] = { wz_str_create("wow1"), wz_str_create("wow2"), wz_str_create("wow3") };
		static bool active = true;
		unsigned items[] = { 0, 1, 2 };
		wz_dropdown(ib_window, &selected_text, strs, 3, 70, &active);
	}

	if (0)
	{
		static bool b;
		WzWidget a = wz_command_button(wz_str_create("wow"), &b, ib_window);
		gui_window.gui.focused_widget_index = a.handle;
		wz_command_button(wz_str_create("wow"), &b, ib_window);
		wz_command_button(wz_str_create("wow"), &b, ib_window);
	}

	WzStr names[] = {
		wz_str_create("wow1"),
		wz_str_create("wow2"),
		wz_str_create("wow3"),
	};

	{
		static int items[3] = { 0, 1, 2 };
		static int selected = 0;
		static bool is_selected;

		static unsigned ids[3] = { 1, 2, 3 };
		for (unsigned i = 0; i < 3; ++i)
		{
			ids[i] = WIDGET_LABEL_LIST000 + i;
		}

		//wz_label_list_sorted(names, 3, &items, ids, 200, 50, WZ_WHITE, &selected, &is_selected, ib_window);
	}

	static bool b;
	//wz_command_button(wz_str_create("asd"), &b, ib_window);

	WSDL_WzEnd(&gui_window);

	if (gui_window.gui.copied_text[0])
	{
		SDL_SetClipboardText(gui_window.gui.copied_text);
		gui_window.gui.copied_text[0] = '\0';
	}

	SDL_SetRenderDrawBlendMode(gui_window.renderer, SDL_BLENDMODE_BLEND);
	WSDL_RenderCommandBuffer(gui_window.renderer, &ispc_cmds);
	SDL_RenderPresent(gui_window.renderer);

	unsigned delta_time = SDL_GetTicks() - time_beginning;
	if (delta_time < 42)
	{
		SDL_Delay(42 - delta_time);
	}

	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}

	events_count = 0;

	return SDL_APP_CONTINUE;
}

// -----------------------------------------------------------------------
// ISPC layout test
//
// Layout under test:
//
//   root (chunk 0, slot 0)  800x600, vertical, pad=10, gap=5
//   └── chunk 1
//       ├── slot 0  fixed   200 x 30
//       ├── slot 1  flex=1  (takes remaining height)
//       └── slot 2  fixed   200 x 40
//
// Expected after wz_layout():
//   slot 0: x=10  y=10  w=200 h=30
//   slot 1: x=10  y=45  w=200 h=<800-30-40-2*5-2*10> = 700
//   slot 2: x=10  y=750 w=200 h=40
// -----------------------------------------------------------------------
static void wz_layout_ispc_test(void)
{
#define TEST_CHUNK_SIZE 8

	// WzChunk and WzSlot types come from WzLayout_ispc.h
	struct WzChunk chunks[2];
	struct WzSlot  slots[2];   // one SOA group per chunk

	memset(chunks, 0, sizeof(chunks));
	memset(slots, 0, sizeof(slots));

	// ---- chunk 0: root ----
	chunks[0].pad_left = 10;
	chunks[0].pad_right = 10;
	chunks[0].pad_top = 10;
	chunks[0].pad_bottom = 10;
	chunks[0].child_gap = 5;
	chunks[0].is_horizontal = 0;
	chunks[0].child_count = 3;
	chunks[0].parent_chunk = 0;
	chunks[0].parent_slot = 0;
	chunks[0].cursor_x = chunks[0].pad_left;
	chunks[0].cursor_y = chunks[0].pad_top;

	// root available space = window size (written into slot 0 of chunk 0)
	slots[0].avail_width[0] = 800;
	slots[0].avail_height[0] = 600;

	// ---- chunk 1: three children of root ----
	chunks[1].pad_left = 0;
	chunks[1].pad_right = 0;
	chunks[1].pad_top = 0;
	chunks[1].pad_bottom = 0;
	chunks[1].child_gap = 0;
	chunks[1].is_horizontal = 0;   // vertical
	chunks[1].child_count = 3;
	chunks[1].parent_chunk = 0;
	chunks[1].parent_slot = 0;
	chunks[1].cursor_x = 0;
	chunks[1].cursor_y = 0;

	slots[1].min_width[0] = 200;  slots[1].min_height[0] = 30;  slots[1].flex[0] = 0;
	slots[1].min_width[1] = 200;  slots[1].min_height[1] = 0;   slots[1].flex[1] = 1;
	slots[1].min_width[2] = 200;  slots[1].min_height[2] = 40;  slots[1].flex[2] = 0;

	wz_layout_chunks(chunks, slots, 2);

	SDL_Log("---- wz_layout ISPC test ----");
	for (int chunk = 0; chunk < 2; ++chunk)
	{
		for (int slot = 0; slot < TEST_CHUNK_SIZE; ++slot)
		{
			float w = slots[chunk].abs_width[slot];
			float h = slots[chunk].abs_height[slot];
			if (w == 0.f && h == 0.f) continue;

			SDL_Log("  chunk %d  slot %d :  x=%.0f  y=%.0f  w=%.0f  h=%.0f",
				chunk, slot,
				slots[chunk].abs_x[slot], slots[chunk].abs_y[slot],
				w, h);
		}
	}
	SDL_Log("------------------------------");
}

// -----------------------------------------------------------------------
// wz_layout_draw_test  –  visual verification of all ISPC layout features.
//
// Layout tree (vertical root, 4 feature rows):
//   Chunk 0 (root, vertical)
//     Chunk 1 → row 0 (red):    MARGINS      – middle child has margin_l/r=24
//     Chunk 2 → row 1 (green):  MAX WIDTH    – 3 flex children, middle capped at 100px
//     Chunk 3 → row 2 (blue):   CROSS-ALIGN  – 4 children: top/ref/center/bottom  + borders
//     Chunk 4 → row 3 (yellow): SHRINK-TO-H  – shrink_h=1, row stays at content height
//
// chunks[5..BENCH_CHUNKS-1]: self-referential benchmark noise (no visual effect)
// -----------------------------------------------------------------------
#define BENCH_CHUNKS 1024
static void wz_layout_draw_test(SDL_Renderer* renderer, WzDrawCommandBuffer* out)
{
	static struct WzChunk chunks[BENCH_CHUNKS];
	static struct WzSlot  slots[BENCH_CHUNKS];
	memset(chunks, 0, sizeof(chunks));
	memset(slots, 0, sizeof(slots));

	// -----------------------------------------------------------------
	// Chunk 0: root  (vertical, 4 rows)
	// -----------------------------------------------------------------
	chunks[0].pad_left = 16; chunks[0].pad_right = 16;
	chunks[0].pad_top = 16; chunks[0].pad_bottom = 16;
	chunks[0].child_gap = 12;
	chunks[0].child_count = 4;
	chunks[0].is_horizontal = 0;
	chunks[0].parent_chunk = 0;  chunks[0].parent_slot = 0;
	chunks[0].cursor_x = 16; chunks[0].cursor_y = 16;
	slots[0].avail_width[0] = WINDOW_WIDTH;
	slots[0].avail_height[0] = WINDOW_HEIGHT;
	// flex[3]=3 matches chunks[0].flex_total (accumulated from chunk 2's 3 flex children),
	// so the yellow shrink row receives ALL remaining window height — then shrink_h clamps it.
	slots[0].flex[3] = 3;

	// -----------------------------------------------------------------
	// Chunk 1: MARGINS demo  (red row)
	//   3 children. Child[1] has margin_l=margin_r=24.
	//   Visible: child[1] box is inset 24px from its allocated footprint.
	// -----------------------------------------------------------------
	chunks[1].pad_left = 8;  chunks[1].pad_right = 8;
	chunks[1].pad_top = 8;  chunks[1].pad_bottom = 8;
	chunks[1].child_gap = 8;
	chunks[1].child_count = 3;
	chunks[1].is_horizontal = 1;
	chunks[1].parent_chunk = 0;  chunks[1].parent_slot = 0;
	chunks[1].cursor_x = 8;  chunks[1].cursor_y = 8;
	slots[1].min_width[0] = 100;  slots[1].min_height[0] = 50;
	slots[1].min_width[1] = 100;  slots[1].min_height[1] = 50;
	slots[1].margin_left[1] = 24; slots[1].margin_right[1] = 24; // <-- margins
	slots[1].min_width[2] = 100;  slots[1].min_height[2] = 50;

	// -----------------------------------------------------------------
	// Chunk 2: MAX WIDTH demo  (green row)
	//   3 flex=1 children. Child[1] has max_w=100 — stays narrow; others grow.
	// -----------------------------------------------------------------
	chunks[2].pad_left = 8;  chunks[2].pad_right = 8;
	chunks[2].pad_top = 8;  chunks[2].pad_bottom = 8;
	chunks[2].child_gap = 8;
	chunks[2].child_count = 3;
	chunks[2].is_horizontal = 1;
	chunks[2].parent_chunk = 0;  chunks[2].parent_slot = 1;
	chunks[2].cursor_x = 8;  chunks[2].cursor_y = 8;
	slots[2].min_width[0] = 60;  slots[2].min_height[0] = 50;  slots[2].flex[0] = 1;
	slots[2].min_width[1] = 60;  slots[2].min_height[1] = 50;  slots[2].flex[1] = 1;
	slots[2].max_width[1] = 100; // <-- max width cap
	slots[2].min_width[2] = 60;  slots[2].min_height[2] = 50;  slots[2].flex[2] = 1;

	// -----------------------------------------------------------------
	// Chunk 3: CROSS-AXIS ALIGNMENT demo  (blue row)  + visible border
	//   4 children, same width, different heights:
	//     [0] h=40  cross_align=0    → top
	//     [1] h=90  cross_align=0    → reference (tallest, defines inner_h)
	//     [2] h=40  cross_align=0.5  → vertically centered
	//     [3] h=40  cross_align=1.0  → bottom
	// -----------------------------------------------------------------
	chunks[3].pad_left = 8;  chunks[3].pad_right = 8;
	chunks[3].pad_top = 8;  chunks[3].pad_bottom = 8;
	chunks[3].border_left = 3;  chunks[3].border_right = 3;
	chunks[3].border_top = 3;  chunks[3].border_bottom = 3;
	chunks[3].child_gap = 8;
	chunks[3].child_count = 4;
	chunks[3].is_horizontal = 1;
	chunks[3].parent_chunk = 0;  chunks[3].parent_slot = 2;
	chunks[3].cursor_x = 8 + 3;  // pad + border
	chunks[3].cursor_y = 8 + 3;
	slots[3].min_width[0] = 90;  slots[3].min_height[0] = 40;  slots[3].cross_align[0] = 0.0f;
	slots[3].min_width[1] = 90;  slots[3].min_height[1] = 90;  slots[3].cross_align[1] = 0.0f; // ref
	slots[3].min_width[2] = 90;  slots[3].min_height[2] = 40;  slots[3].cross_align[2] = 0.5f;
	slots[3].min_width[3] = 90;  slots[3].min_height[3] = 40;  slots[3].cross_align[3] = 1.0f;

	// -----------------------------------------------------------------
	// Chunk 4: SHRINK-TO-HEIGHT demo  (yellow row)
	//   slots[0].flex[3]=3 gives this row all extra window height.
	//   shrink_h=1 clamps it back to its natural content height.
	//   Without shrink_h the yellow row would fill the rest of the screen.
	// -----------------------------------------------------------------
	chunks[4].pad_left = 8;  chunks[4].pad_right = 8;
	chunks[4].pad_top = 8;  chunks[4].pad_bottom = 8;
	chunks[4].child_gap = 8;
	chunks[4].child_count = 3;
	chunks[4].is_horizontal = 1;
	chunks[4].parent_chunk = 0;  chunks[4].parent_slot = 3;
	chunks[4].cursor_x = 8;  chunks[4].cursor_y = 8;
	chunks[4].shrink_height = 1;  // <-- shrink
	slots[4].min_width[0] = 80;  slots[4].min_height[0] = 50;
	slots[4].min_width[1] = 80;  slots[4].min_height[1] = 50;
	slots[4].min_width[2] = 80;  slots[4].min_height[2] = 50;

	// Benchmark chunks: self-referential so Pass 1 writes into own slots only
	for (int i = 5; i < BENCH_CHUNKS; ++i)
	{
		chunks[i].pad_left = 4;  chunks[i].pad_right = 4;
		chunks[i].child_gap = 2;
		chunks[i].is_horizontal = i % 2;
		chunks[i].child_count = 4;
		chunks[i].parent_chunk = i;
		chunks[i].parent_slot = 0;
		chunks[i].cursor_x = 4;  chunks[i].cursor_y = 4;
		for (int j = 0; j < 4; ++j)
		{
			slots[i].min_width[j] = 40.f + (float)(j * 10);
			slots[i].min_height[j] = 20.f + (float)(j * 5);
		}
	}

	Uint64 t0 = SDL_GetPerformanceCounter();
	wz_layout_chunks(chunks, slots, BENCH_CHUNKS);
	Uint64 t1 = SDL_GetPerformanceCounter();
	double ms = (double)(t1 - t0) * 1000.0 / (double)SDL_GetPerformanceFrequency();

	SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

	// -----------------------------------------------------------------
	// Draw row backgrounds  (slots[0][0..3])
	// -----------------------------------------------------------------
	static const unsigned row_col[4] = {
		WZ_RGBA(220,  80,  80, 150),   // red    – margins
		WZ_RGBA(60, 170,  60, 150),   // green  – max_w
		WZ_RGBA(50,  90, 210, 150),   // blue   – cross_align
		WZ_RGBA(210, 190,  50, 150),   // yellow – shrink
	};
	for (int j = 0; j < 4; ++j)
	{
		wz_ispc_push_rect(out, &slots[0], j, row_col[j]);
		SDL_FRect r = { slots[0].abs_x[j], slots[0].abs_y[j],
						slots[0].abs_width[j], slots[0].abs_height[j] };
		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 200);
		SDL_RenderRect(renderer, &r);
	}

	// -----------------------------------------------------------------
	// Row 0 (red): MARGINS  – slots[1][0..2]
	//   Child[1] is lighter; also draw its margin footprint as dim rect.
	// -----------------------------------------------------------------
	static const unsigned margin_col[3] = {
		WZ_RGBA(150, 40, 40, 230), WZ_RGBA(255, 140, 140, 230), WZ_RGBA(150, 40, 40, 230)
	};
	for (int j = 0; j < 3; ++j)
	{
		wz_ispc_push_rect(out, &slots[1], j, margin_col[j]);
		SDL_FRect r = { slots[1].abs_x[j], slots[1].abs_y[j],
						slots[1].abs_width[j], slots[1].abs_height[j] };
		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 160);
		SDL_RenderRect(renderer, &r);
	}
	// Margin footprint of child[1]: the area including its margins
	{
		SDL_FRect fp = {
			slots[1].abs_x[1] - slots[1].margin_left[1],
			slots[1].abs_y[1],
			slots[1].abs_width[1] + slots[1].margin_left[1] + slots[1].margin_right[1],
			slots[1].abs_height[1]
		};
		SDL_SetRenderDrawColor(renderer, 255, 220, 100, 120);
		SDL_RenderRect(renderer, &fp);
	}

	// -----------------------------------------------------------------
	// Row 1 (green): MAX WIDTH  – slots[2][0..2]
	//   Child[1] (middle, lighter) is the capped one.
	// -----------------------------------------------------------------
	static const unsigned max_col[3] = {
		WZ_RGBA(30, 130, 30, 230), WZ_RGBA(160, 255, 160, 230), WZ_RGBA(30, 130, 30, 230)
	};
	for (int j = 0; j < 3; ++j)
	{
		wz_ispc_push_rect(out, &slots[2], j, max_col[j]);
		SDL_FRect r = { slots[2].abs_x[j], slots[2].abs_y[j],
						slots[2].abs_width[j], slots[2].abs_height[j] };
		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 160);
		SDL_RenderRect(renderer, &r);
	}

	// -----------------------------------------------------------------
	// Row 2 (blue): CROSS-ALIGN  – slots[3][0..3]
	//   Draw border stripes first, then children.
	// -----------------------------------------------------------------
	{
		float bx = slots[0].abs_x[2], by = slots[0].abs_y[2];
		float bw = slots[0].abs_width[2], bh = slots[0].abs_height[2];
		float bl = chunks[3].border_left, br = chunks[3].border_right;
		float bt = chunks[3].border_top, bb = chunks[3].border_bottom;
		unsigned border_color = WZ_RGBA(180, 210, 255, 255);
		wz_push_filled_rect(out, bx, by, bw, bt, border_color);
		wz_push_filled_rect(out, bx, by + bh - bb, bw, bb, border_color);
		wz_push_filled_rect(out, bx, by, bl, bh, border_color);
		wz_push_filled_rect(out, bx + bw - br, by, br, bh, border_color);
	}
	static const unsigned align_col[4] = {
		WZ_RGBA(20,  60, 170, 230),   // top
		WZ_RGBA(100, 160, 255, 230),   // reference (tallest)
		WZ_RGBA(20,  60, 170, 230),   // center
		WZ_RGBA(20,  60, 170, 230),   // bottom
	};
	for (int j = 0; j < 4; ++j)
	{
		wz_ispc_push_rect(out, &slots[3], j, align_col[j]);
		SDL_FRect r = { slots[3].abs_x[j], slots[3].abs_y[j],
						slots[3].abs_width[j], slots[3].abs_height[j] };
		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 160);
		SDL_RenderRect(renderer, &r);
	}

	// -----------------------------------------------------------------
	// Row 3 (yellow): SHRINK  – slots[4][0..2]
	// -----------------------------------------------------------------
	static const unsigned shrink_col[3] = {
		WZ_RGBA(170, 150, 20, 230), WZ_RGBA(255, 240, 90, 230), WZ_RGBA(170, 150, 20, 230)
	};
	for (int j = 0; j < 3; ++j)
	{
		wz_ispc_push_rect(out, &slots[4], j, shrink_col[j]);
		SDL_FRect r = { slots[4].abs_x[j], slots[4].abs_y[j],
						slots[4].abs_width[j], slots[4].abs_height[j] };
		SDL_SetRenderDrawColor(renderer, 255, 255, 255, 160);
		SDL_RenderRect(renderer, &r);
	}

	// -----------------------------------------------------------------
	// Feature labels
	// -----------------------------------------------------------------
	static const char* const labels[4] = {
		"MARGINS: child[1] has margin_l/r=24 (yellow outline = footprint)",
		"MAX_W:   child[1] flex=1 but capped at 100px; others expand",
		"CROSS_ALIGN: [0]=top  [1]=ref  [2]=center  [3]=bottom  (+ 3px border)",
		"SHRINK_H: row has flex but shrink_h=1 keeps it at content height",
	};
	for (int j = 0; j < 4; ++j)
	{
		int llen = (int)SDL_strlen(labels[j]);
		render_text(renderer, &fonts[0], labels[j],
			(int)slots[0].abs_x[j] + 4,
			(int)slots[0].abs_y[j] + 2,
			font_heights[0], llen);
	}

	// -----------------------------------------------------------------
	// Timing label (top-right)
	// -----------------------------------------------------------------
	char buf[40];
	int len = SDL_snprintf(buf, sizeof(buf), "ISPC: %.4f ms", ms);
	float tw = 0, th = 0;
	get_string_size(buf, 0, len, 0, &tw, &th);
	wz_push_filled_rect(out, WINDOW_WIDTH - tw - 14, 6, tw + 10, th + 4, WZ_RGBA(0, 0, 0, 160));
	render_text(renderer, &fonts[0], buf, (int)(WINDOW_WIDTH - tw - 9), 8, th, len);
}

void wz_layout_new()
{
#if 0
	chunks.available_width[0][0] = FLT_MAX;
	chunks.available_height[0][0] = FLT_MAX;

#if 0
	// --- Init root ---
	chunks.minimum_width[0][0] = 1000;
	chunks.minimum_height[0][0] = 1000;
	chunks.available_width[0][0] = 1000;
	chunks.available_height[0][0] = 1000;
	chunks.absolute_width[0][0] = 1000;
	chunks.absolute_height[0][0] = 1000;

	chunks.padding_left[0] = 5;
	chunks.padding_right[0] = 5;
	chunks.padding_top[0] = 5;
	chunks.padding_bottom[0] = 5;
	chunks.child_gap[0] = 20;
	chunks.is_horizontal[0] = false;
	chunks.children_count[0] = 0;
	chunks.children_flex_total[0] = 0;
	chunks.layout_cursor_x[0] = 5;
	chunks.layout_cursor_y[0] = 5;

	wz->widgets[0].actual_x = chunks.absolute_x[0][0];
	wz->widgets[0].actual_y = chunks.absolute_y[0][0];
	wz->widgets[0].actual_w = chunks.absolute_width[0][0];
	wz->widgets[0].actual_h = chunks.absolute_height[0][0];

	// --- Widget creation ---
	WzWidgetNew parent = { .child_chunk = 1 };

	WzWidgetNew w = create_widget(&parent);
	chunks.minimum_width[w.chunk][w.index_in_chunk] = 50;
	chunks.minimum_height[w.chunk][w.index_in_chunk] = 50;

	for (unsigned i = 0; i < 2; ++i)
	{
		WzWidgetNew w = create_widget(&parent);
		chunks.minimum_width[w.chunk][w.index_in_chunk] = 10;
		chunks.minimum_height[w.chunk][w.index_in_chunk] = 10;
		chunks.flex[w.chunk][w.index_in_chunk] = (float)(1 + i);
	}
#else

#endif

	// ----------------------------------------------------------------
	// Pass 1: bottom-up minimum size
	// ----------------------------------------------------------------
	for (int i = MAX_NUM_CHUNKS - 1; i > 0; --i)
	{
		unsigned parent_chunk = chunks_data[i].parent_chunk;
		unsigned parent_slot = chunks_data[i].parent_index_inside_chunk;

		float total_width = 0, total_height = 0;
		float biggest_width = 0, biggest_height = 0;
		float total_flex = 0;

		float* minimum_width = chunks.minimum_width[i];
		float* minimum_height = chunks.minimum_height[i];
		float* flex = chunks.flex[i];

		for (unsigned j = 0; j < CHUNK_SIZE; ++j)
		{
			total_width += minimum_width[j];
			total_height += minimum_height[j];
			biggest_width = fmaxf(biggest_width, minimum_width[j]);
			biggest_height = fmaxf(biggest_height, minimum_height[j]);
			total_flex += flex[j];
		}

		chunks.children_flex_total[parent_chunk] += (unsigned)total_flex;

		total_width = fmaxf(total_width, chunks.minimum_width[parent_chunk][parent_slot]);
		total_height = fmaxf(total_height, chunks.minimum_height[parent_chunk][parent_slot]);

		chunks.minimum_width[parent_chunk][parent_slot] = chunks.is_horizontal[parent_chunk] ? total_width : biggest_width;
		chunks.minimum_height[parent_chunk][parent_slot] = !chunks.is_horizontal[parent_chunk] ? total_height : biggest_height;
	}

	// ----------------------------------------------------------------
	// Pass 2: top-down available space
	// ----------------------------------------------------------------
	for (int i = 0; i < MAX_NUM_CHUNKS; ++i)
	{
		unsigned parent_chunk = chunks_data[i].parent_chunk;
		unsigned parent_slot = chunks_data[i].parent_index_inside_chunk;

		float space_width = chunks.available_width[parent_chunk][parent_slot];
		float space_height = chunks.available_height[parent_chunk][parent_slot];

		space_width -= chunks.padding_left[parent_chunk] + chunks.padding_right[parent_chunk];
		space_height -= chunks.padding_top[parent_chunk] + chunks.padding_bottom[parent_chunk];
		space_width -= chunks.is_horizontal[parent_chunk] ? chunks.child_gap[parent_chunk] * (chunks.children_count[parent_chunk] - 1) : 0;
		space_height -= chunks.is_horizontal[parent_chunk] ? 0 : chunks.child_gap[parent_chunk] * (chunks.children_count[parent_chunk] - 1);

		float* minimum_width = chunks.minimum_width[i];
		float* minimum_height = chunks.minimum_height[i];
		float* available_width = chunks.available_width[i];
		float* available_height = chunks.available_height[i];

		for (unsigned j = 0; j < CHUNK_SIZE; ++j)
		{
			space_width -= minimum_width[j];
			space_height -= minimum_height[j];
			available_width[j] += minimum_width[j];
			available_height[j] += minimum_height[j];
		}

		float width_per_flex = chunks.children_flex_total[parent_chunk] > 0 ? space_width / chunks.children_flex_total[parent_chunk] : 0;
		float height_per_flex = chunks.children_flex_total[parent_chunk] > 0 ? space_height / chunks.children_flex_total[parent_chunk] : 0;

		float* flex = chunks.flex[i];
		bool   is_horizontal = chunks.is_horizontal[parent_chunk];

		for (unsigned j = 0; j < CHUNK_SIZE; ++j)
		{
			available_width[j] += is_horizontal ? flex[j] * width_per_flex : 0;
			available_height[j] += !is_horizontal ? flex[j] * height_per_flex : 0;
		}
	}

	// ----------------------------------------------------------------
	// Pass 3: available -> absolute
	// ----------------------------------------------------------------
	for (int i = 0; i < MAX_NUM_CHUNKS; ++i)
	{
		float* available_width = chunks.available_width[i];
		float* available_height = chunks.available_height[i];
		float* absolute_width = chunks.absolute_width[i];
		float* absolute_height = chunks.absolute_height[i];

		for (unsigned j = 0; j < CHUNK_SIZE; ++j)
		{
			absolute_width[j] = available_width[j];
			absolute_height[j] = available_height[j];
		}
	}

	// ----------------------------------------------------------------
	// Pass 4: assert parent space non-negative (debug only)
	// ----------------------------------------------------------------
	for (int i = 1; i < MAX_NUM_CHUNKS; ++i)
	{
		unsigned parent_chunk = chunks_data[i].parent_chunk;
		unsigned parent_slot = chunks_data[i].parent_index_inside_chunk;
		wz_assert(chunks.available_width[parent_chunk][parent_slot] >= 0);
		wz_assert(chunks.available_height[parent_chunk][parent_slot] >= 0);
	}

	// ----------------------------------------------------------------
	// Pass 5: write widget positions (serial)
	// ----------------------------------------------------------------
	for (unsigned i = 0; i < MAX_NUM_CHUNKS; ++i)
	{
		unsigned parent_chunk = chunks_data[i].parent_chunk;
		unsigned parent_slot = chunks_data[i].parent_index_inside_chunk;

		float parent_absolute_x = chunks.absolute_x[parent_chunk][parent_slot];
		float parent_absolute_y = chunks.absolute_y[parent_chunk][parent_slot];
		bool  is_horizontal = chunks.is_horizontal[parent_chunk];
		float gap = chunks.child_gap[parent_chunk];
		; \
			for (unsigned j = 0; j < CHUNK_SIZE; ++j)
			{
				float absolute_width = chunks.absolute_width[i][j];
				float absolute_height = chunks.absolute_height[i][j];

				chunks.absolute_x[i][j] = parent_absolute_x + chunks.layout_cursor_x[parent_chunk];
				chunks.absolute_y[i][j] = parent_absolute_y + chunks.layout_cursor_y[parent_chunk];

				chunks.layout_cursor_x[parent_chunk] += is_horizontal ? absolute_width + gap : 0;
				chunks.layout_cursor_y[parent_chunk] += !is_horizontal ? absolute_height + gap : 0;
			}
	}

	unsigned widgets_count = 0;

	for (unsigned i = 0; i < MAX_NUM_CHUNKS; ++i)
	{
		for (unsigned j = 0; j < CHUNK_SIZE; ++j)
		{
			if (chunks.absolute_width[i][j])
			{
				wz->widgets[widgets_count].actual_w = chunks.absolute_width[i][j];
				wz->widgets[widgets_count].actual_h = chunks.absolute_height[i][j];
				wz->widgets[widgets_count].actual_x = chunks.absolute_x[i][j];
				wz->widgets[widgets_count].actual_y = chunks.absolute_y[i][j];

				widgets_count++;
				widgets_count &= MAX_NUM_WIDGETS - 1;
				wz_assert(widgets_count < MAX_NUM_WIDGETS);
			}
		}
	}
#endif
}