#define SDL_MAIN_USE_CALLBACKS 1  /* use the callbacks instead of main() */

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_image/SDL_image.h>
#include <stdio.h>
#include "WzGuiCore.h"
#include "WzLayoutScalar.h"
#define __ISPC_STRUCT_WzChunk__  // already defined in WzGuiCore.h
#include "WzLayout_ispc.h"  // generated by: ispc WzLayout.ispc --target=avx2-i32x8 --header-outfile=WzLayout_ispc.h
#define _USE_MATH_DEFINES
#include <math.h>
#include <d3dcompiler.h>
#pragma comment(lib, "d3dcompiler")

// ---- HLSL Shader Sources (SM5.1, register spaces for SDL3 D3D12 backend) ----
static const char vs_hlsl_source[] =
	"cbuffer VertexUniforms : register(b0, space1) {\n"
	"    float2 screen_size;\n"
	"};\n"
	"struct VSInput {\n"
	"    float2 position : TEXCOORD0;\n"
	"    uint   color    : TEXCOORD1;\n"
	"    float2 texcoord : TEXCOORD2;\n"
	"};\n"
	"struct VSOutput {\n"
	"    float4 position : SV_Position;\n"
	"    float4 color    : TEXCOORD0;\n"
	"    float2 texcoord : TEXCOORD1;\n"
	"};\n"
	"VSOutput main(VSInput input) {\n"
	"    VSOutput output;\n"
	"    output.position = float4(\n"
	"        (input.position.x / screen_size.x) * 2.0 - 1.0,\n"
	"        1.0 - (input.position.y / screen_size.y) * 2.0,\n"
	"        0.0, 1.0);\n"
	"    output.color = float4(\n"
	"        (float)((input.color >> 24) & 0xFF) / 255.0,\n"
	"        (float)((input.color >> 16) & 0xFF) / 255.0,\n"
	"        (float)((input.color >>  8) & 0xFF) / 255.0,\n"
	"        (float)( input.color        & 0xFF) / 255.0);\n"
	"    output.texcoord = input.texcoord;\n"
	"    return output;\n"
	"}\n";

static const char ps_hlsl_source[] =
	"Texture2D tex : register(t0, space2);\n"
	"SamplerState samp : register(s0, space2);\n"
	"struct PSInput {\n"
	"    float4 position : SV_Position;\n"
	"    float4 color    : TEXCOORD0;\n"
	"    float2 texcoord : TEXCOORD1;\n"
	"};\n"
	"float4 main(PSInput input) : SV_Target {\n"
	"    return input.color * tex.Sample(samp, input.texcoord);\n"
	"}\n";

// ---- Shader Compilation ----
static SDL_GPUShader* compile_hlsl_shader(
	SDL_GPUDevice* device, const char* source,
	const char* target, SDL_GPUShaderStage stage,
	Uint32 num_samplers, Uint32 num_uniform_buffers)
{
	ID3DBlob* code = NULL;
	ID3DBlob* errors = NULL;
	HRESULT hr = D3DCompile(source, strlen(source), NULL, NULL, NULL,
		"main", target, 0, 0, &code, &errors);
	if (FAILED(hr)) {
		if (errors) {
			SDL_Log("Shader compile error: %s",
				(const char*)errors->lpVtbl->GetBufferPointer(errors));
			errors->lpVtbl->Release(errors);
		}
		return NULL;
	}
	if (errors) errors->lpVtbl->Release(errors);

	SDL_GPUShaderCreateInfo info = {
		.code = (const Uint8*)code->lpVtbl->GetBufferPointer(code),
		.code_size = code->lpVtbl->GetBufferSize(code),
		.entrypoint = "main",
		.format = SDL_GPU_SHADERFORMAT_DXBC,
		.stage = stage,
		.num_samplers = num_samplers,
		.num_storage_textures = 0,
		.num_storage_buffers = 0,
		.num_uniform_buffers = num_uniform_buffers,
	};
	SDL_GPUShader* shader = SDL_CreateGPUShader(device, &info);
	code->lpVtbl->Release(code);
	return shader;
}

// ---- GPU Texture Upload ----
static SDL_GPUTexture* gpu_upload_texture(SDL_GPUDevice* device,
	const unsigned char* rgba, int w, int h)
{
	SDL_GPUTexture* tex = SDL_CreateGPUTexture(device, &(SDL_GPUTextureCreateInfo){
		.type = SDL_GPU_TEXTURETYPE_2D,
		.format = SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM,
		.usage = SDL_GPU_TEXTUREUSAGE_SAMPLER,
		.width = (Uint32)w, .height = (Uint32)h,
		.layer_count_or_depth = 1, .num_levels = 1,
		.sample_count = SDL_GPU_SAMPLECOUNT_1,
	});
	assert(tex);

	SDL_GPUTransferBuffer* tbuf = SDL_CreateGPUTransferBuffer(device,
		&(SDL_GPUTransferBufferCreateInfo){
			.usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD,
			.size = (Uint32)(w * h * 4),
		});
	void* mapped = SDL_MapGPUTransferBuffer(device, tbuf, false);
	memcpy(mapped, rgba, w * h * 4);
	SDL_UnmapGPUTransferBuffer(device, tbuf);

	SDL_GPUCommandBuffer* cmd = SDL_AcquireGPUCommandBuffer(device);
	SDL_GPUCopyPass* copy = SDL_BeginGPUCopyPass(cmd);
	SDL_UploadToGPUTexture(copy,
		&(SDL_GPUTextureTransferInfo){
			.transfer_buffer = tbuf,
			.pixels_per_row = (Uint32)w,
			.rows_per_layer = (Uint32)h,
		},
		&(SDL_GPUTextureRegion){
			.texture = tex,
			.w = (Uint32)w, .h = (Uint32)h, .d = 1,
		}, false);
	SDL_EndGPUCopyPass(copy);
	SDL_SubmitGPUCommandBuffer(cmd);
	SDL_ReleaseGPUTransferBuffer(device, tbuf);
	return tex;
}

static SDL_GPUTexture* gpu_upload_alpha_atlas(SDL_GPUDevice* device,
	const unsigned char* bitmap, int w, int h)
{
	unsigned char* rgba = (unsigned char*)malloc(w * h * 4);
	for (int i = 0; i < w * h; i++) {
		rgba[i * 4 + 0] = 255;
		rgba[i * 4 + 1] = 255;
		rgba[i * 4 + 2] = 255;
		rgba[i * 4 + 3] = bitmap[i];
	}
	SDL_GPUTexture* tex = gpu_upload_texture(device, rgba, w, h);
	free(rgba);
	return tex;
}

#define CONCAT(a, b) a##b
#define ITEM(name, num) CONCAT(name, num),

// These must be hard-coded because the preprocessor can't do "offset + 1"
#define GEN_2(n, o0, o1)      ITEM(n, o0) ITEM(n, o1)
#define GEN_4(n, o0, o1, o2, o3) GEN_2(n, o0, o1) GEN_2(n, o2, o3)

// To avoid writing 512 arguments, we use a slightly different "Nested" approach:
#define B000(n, p) ITEM(n, p##0) ITEM(n, p##1) ITEM(n, p##2) ITEM(n, p##3) ITEM(n, p##4) ITEM(n, p##5) ITEM(n, p##6) ITEM(n, p##7)
#define B00(n, p)  B000(n, p##0) B000(n, p##1) B000(n, p##2) B000(n, p##3) B000(n, p##4) B000(n, p##5) B000(n, p##6) B000(n, p##7)

// This will generate items 000 through 511 (formatted as 3 digits to avoid math)
#define GEN_512_SAFE(n) \
    B00(n, 0) B00(n, 1) B00(n, 2) B00(n, 3) B00(n, 4) B00(n, 5) B00(n, 6) B00(n, 7)

enum
{
	WIDGET_INPUT_BOX1 = 1,
	WIDGET_INPUT_BOX2,
	WIDGET_INPUT_BOX3,
	WIDGET_DROPDOWN1,
	WIDGET_VBOX1,
	WIDGET_LABEL1,
	GEN_512_SAFE(WIDGET_LABEL_LIST)
};


static void wz_layout_ispc_test(void);
static void wz_layout_draw_test(WzDrawCommandBuffer* out);
static void WSDL_RenderCommandBuffer(WzDrawCommandBuffer* buf);

#define MAX_NUM_EVENTS 128
unsigned events_count;
WzEvent events[MAX_NUM_EVENTS];

static unsigned short sdl_keymod_to_wz(SDL_Keymod sdl_mod)
{
	unsigned short wz_mod = WZ_KMOD_NONE;

	if (sdl_mod & SDL_KMOD_LSHIFT) wz_mod |= WZ_KMOD_LSHIFT;
	if (sdl_mod & SDL_KMOD_RSHIFT) wz_mod |= WZ_KMOD_RSHIFT;
	if (sdl_mod & SDL_KMOD_LCTRL)  wz_mod |= WZ_KMOD_LCTRL;
	if (sdl_mod & SDL_KMOD_RCTRL)  wz_mod |= WZ_KMOD_RCTRL;
	if (sdl_mod & SDL_KMOD_LALT)   wz_mod |= WZ_KMOD_LALT;
	if (sdl_mod & SDL_KMOD_RALT)   wz_mod |= WZ_KMOD_RALT;
	if (sdl_mod & SDL_KMOD_LGUI)   wz_mod |= WZ_KMOD_LGUI;
	if (sdl_mod & SDL_KMOD_RGUI)   wz_mod |= WZ_KMOD_RGUI;

	return wz_mod;
}

// Convert SDL3 scancode + modifiers to WZ keycode
// Returns 0-127 for ASCII characters, 128+ for special keys
WZ_Keycode wz_sdl_scancode_to_keycode(SDL_Scancode scancode, SDL_Keymod modifiers)
{
	bool shift = (modifiers & (SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT)) != 0;
	bool caps = (modifiers & SDL_KMOD_CAPS) != 0;

	// Letters A-Z
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		char base = 'a' + (scancode - SDL_SCANCODE_A);
		// Caps lock XOR shift gives uppercase
		if (caps != shift) {
			return base - 32; // Uppercase ASCII
		}
		return base; // Lowercase ASCII
	}

	// Numbers 1-9, 0
	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		if (shift) {
			const char symbols[] = "!@#$%^&*(";
			return symbols[scancode - SDL_SCANCODE_1];
		}
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) {
		return shift ? ')' : '0';
	}

	// Punctuation and special keys (ASCII range)
	switch (scancode) {
	case SDL_SCANCODE_SPACE:      return ' ';
	case SDL_SCANCODE_RETURN:     return '\n';
	case SDL_SCANCODE_ESCAPE:     return 27;
	case SDL_SCANCODE_BACKSPACE:  return '\b';
	case SDL_SCANCODE_TAB:        return '\t';

	case SDL_SCANCODE_MINUS:      return shift ? '_' : '-';
	case SDL_SCANCODE_EQUALS:     return shift ? '+' : '=';
	case SDL_SCANCODE_LEFTBRACKET:  return shift ? '{' : '[';
	case SDL_SCANCODE_RIGHTBRACKET: return shift ? '}' : ']';
	case SDL_SCANCODE_BACKSLASH:    return shift ? '|' : '\\';
	case SDL_SCANCODE_SEMICOLON:    return shift ? ':' : ';';
	case SDL_SCANCODE_APOSTROPHE:   return shift ? '"' : '\'';
	case SDL_SCANCODE_GRAVE:        return shift ? '~' : '`';
	case SDL_SCANCODE_COMMA:        return shift ? '<' : ',';
	case SDL_SCANCODE_PERIOD:       return shift ? '>' : '.';
	case SDL_SCANCODE_SLASH:        return shift ? '?' : '/';
	}

	// Extended keys (128+)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK:     return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1:           return WZ_KEY_F1;
	case SDL_SCANCODE_F2:           return WZ_KEY_F2;
	case SDL_SCANCODE_F3:           return WZ_KEY_F3;
	case SDL_SCANCODE_F4:           return WZ_KEY_F4;
	case SDL_SCANCODE_F5:           return WZ_KEY_F5;
	case SDL_SCANCODE_F6:           return WZ_KEY_F6;
	case SDL_SCANCODE_F7:           return WZ_KEY_F7;
	case SDL_SCANCODE_F8:           return WZ_KEY_F8;
	case SDL_SCANCODE_F9:           return WZ_KEY_F9;
	case SDL_SCANCODE_F10:          return WZ_KEY_F10;
	case SDL_SCANCODE_F11:          return WZ_KEY_F11;
	case SDL_SCANCODE_F12:          return WZ_KEY_F12;

	case SDL_SCANCODE_PRINTSCREEN:  return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK:   return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE:        return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT:       return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME:         return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP:       return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE:       return WZ_KEY_DELETE;
	case SDL_SCANCODE_END:          return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN:     return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT:        return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT:         return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN:         return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP:           return WZ_KEY_UP;

	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE:    return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY:  return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS:     return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS:      return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER:     return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1:         return (modifiers & SDL_KMOD_NUM) ? '1' : WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2:         return (modifiers & SDL_KMOD_NUM) ? '2' : WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3:         return (modifiers & SDL_KMOD_NUM) ? '3' : WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4:         return (modifiers & SDL_KMOD_NUM) ? '4' : WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5:         return (modifiers & SDL_KMOD_NUM) ? '5' : WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6:         return (modifiers & SDL_KMOD_NUM) ? '6' : WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7:         return (modifiers & SDL_KMOD_NUM) ? '7' : WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8:         return (modifiers & SDL_KMOD_NUM) ? '8' : WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9:         return (modifiers & SDL_KMOD_NUM) ? '9' : WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0:         return (modifiers & SDL_KMOD_NUM) ? '0' : WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD:    return (modifiers & SDL_KMOD_NUM) ? '.' : WZ_KEY_KP_PERIOD;

	case SDL_SCANCODE_APPLICATION:  return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER:        return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS:    return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13:          return WZ_KEY_F13;
	case SDL_SCANCODE_F14:          return WZ_KEY_F14;
	case SDL_SCANCODE_F15:          return WZ_KEY_F15;
	case SDL_SCANCODE_F16:          return WZ_KEY_F16;
	case SDL_SCANCODE_F17:          return WZ_KEY_F17;
	case SDL_SCANCODE_F18:          return WZ_KEY_F18;
	case SDL_SCANCODE_F19:          return WZ_KEY_F19;
	case SDL_SCANCODE_F20:          return WZ_KEY_F20;
	case SDL_SCANCODE_F21:          return WZ_KEY_F21;
	case SDL_SCANCODE_F22:          return WZ_KEY_F22;
	case SDL_SCANCODE_F23:          return WZ_KEY_F23;
	case SDL_SCANCODE_F24:          return WZ_KEY_F24;

	case SDL_SCANCODE_EXECUTE:      return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP:         return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU:         return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT:       return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP:         return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN:        return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO:         return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT:          return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY:         return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE:        return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND:         return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE:         return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP:     return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN:   return WZ_KEY_VOLUMEDOWN;

	case SDL_SCANCODE_LCTRL:        return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT:       return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT:         return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI:         return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL:        return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT:       return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT:         return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI:         return WZ_KEY_RGUI;

	case SDL_SCANCODE_MODE:         return WZ_KEY_MODE;

	default:
		return WZ_KEY_UNKNOWN;
	}
}

// Helper: Check if keycode is printable ASCII
bool wz_keycode_is_printable(WZ_Keycode keycode)
{
	return keycode >= 32 && keycode <= 126;
}

// Helper: Check if keycode is ASCII (printable or control)
bool wz_keycode_is_ascii(WZ_Keycode keycode)
{
	return keycode >= 0 && keycode < 128;
}

// Helper: Check if keycode is extended (special key)
bool wz_keycode_is_extended(WZ_Keycode keycode)
{
	return keycode >= 128 && keycode < WZ_KEY_COUNT;
}

typedef struct Wsdl
{
	WzKeyboard keyboard;
} Wsdl;

Wsdl wsdl;

typedef struct
{
	SDL_Window* window;
	SDL_GPUDevice* gpu_device;
	SDL_GPUGraphicsPipeline* pipeline;
	SDL_GPUSampler* sampler_nearest;
	SDL_GPUSampler* sampler_linear;
	SDL_GPUTexture* white_texture;
	SDL_GPUBuffer* vertex_buffer;
	SDL_GPUBuffer* index_buffer;
	SDL_GPUTransferBuffer* transfer_vtx;
	SDL_GPUTransferBuffer* transfer_idx;
	WzGui gui;
} WSDL_Context;

WSDL_Context main_window;
WSDL_Context gui_window;


// Color component extraction macros (for RGBA format: 0xRRGGBBAA)
#define WZ_COLOR_R(c) (((c) >> 24) & 0xFF)
#define WZ_COLOR_G(c) (((c) >> 16) & 0xFF)
#define WZ_COLOR_B(c) (((c) >> 8) & 0xFF)
#define WZ_COLOR_A(c) ((c) & 0xFF)
#define WZ_RGBA(r,g,b,a) (((unsigned)(r)<<24)|((unsigned)(g)<<16)|((unsigned)(b)<<8)|(unsigned)(a))

static WzDrawCommandBuffer ispc_cmds;

static void wz_push_filled_rect(WzDrawCommandBuffer* buf, float x, float y, float w, float h, unsigned color)
{
	if (!buf || buf->count >= MAX_NUM_DRAW_COMMANDS - 1) return;
	WzDrawCommand* cmd = &buf->commands[buf->count++];
	cmd->type = DrawCommandType_Rect;
	cmd->x = x; cmd->y = y; cmd->w = w; cmd->h = h; cmd->color = color;
}

static void wz_ispc_push_rect(WzDrawCommandBuffer* buf, const struct WzSlotOld* slot, int lane, unsigned color)
{
	wz_push_filled_rect(buf, slot->abs_x[lane], slot->abs_y[lane], slot->abs_width[lane], slot->abs_height[lane], color);
}

//#define assert(x) void(x)

#define MAX_NUM_TEXTURES_IN_ANIMATION 128

typedef struct Animation
{
	SDL_Texture* textures[MAX_NUM_TEXTURES_IN_ANIMATION];
	unsigned textures_count;
	unsigned w, h;
} Animation;

typedef struct WzWidgetPersistentData
{
	WzWidget widget;
	float transform_x, transform_y;
	float scale_x, scale_y;
	float rotation;

	Animation animation;
	unsigned current_animation_frame;
} WzWidgetPersistentData;

#define MAX_NUM_IMAGE_WIDGETS 32
WzWidgetPersistentData image_widgets[MAX_NUM_IMAGE_WIDGETS];
unsigned image_widgets_count;

WzGui gui;

WzTexture texture;

#define MAX_NUM_RENDERERS 16
#define MAX_NUM_WINDOWS 16


WzState left_mouse;

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 540

bool error;



bool load_animation(SDL_Renderer* renderer, Animation* animation, const char* path)
{
	bool success = true;
	IMG_Animation* anim = IMG_LoadAnimation(path);

	if (!anim)
	{
		return false;
	}

	if (anim->count == MAX_NUM_TEXTURES_IN_ANIMATION)
	{
		SDL_SetError("Loaded to many gifs");
		return false;
	}

	*animation = (Animation){ .textures_count = anim->count, .w = anim->w, .h = anim->h };
	for (int i = 0; i < anim->count; i++)
	{
		animation->textures[i] = SDL_CreateTextureFromSurface(renderer, anim->frames[i]);
		if (!animation->textures[i])
		{
			return false;
		}
	}
}

static void WSDL_RenderCommandBuffer(WzDrawCommandBuffer* buf)
{
	(void)buf;
}

static void WSDL_WzBeginWidgets(WSDL_Context* context)
{
	Uint32 flags = SDL_GetWindowFlags(context->window);
	float mouse_x = 0, mouse_y = 0;
	if (flags & SDL_WINDOW_MOUSE_FOCUS)
	{
		SDL_GetMouseState(&mouse_x, &mouse_y);
	}

	context->gui.mouse_pos.x = mouse_x;
	context->gui.mouse_pos.y = mouse_y;

	wz_begin(WINDOW_WIDTH, WINDOW_HEIGHT,
		events, events_count, true);
}

void WSDL_WzEnd(WSDL_Context* context)
{
	wz_end();
}

#define NS_TO_MS(ns) ((float)(ns) / 1000000.0f)

static float perf_avg(float* samples, unsigned* index, float new_val)
{
	samples[*index % 60] = new_val;
	(*index)++;
	float sum = 0.0f;
	unsigned count = *index < 60 ? *index : 60;
	for (unsigned i = 0; i < count; ++i) sum += samples[i];
	return sum / (float)count;
}

// Sub-timings for WSDL_WzRender (rolling 60-frame averages)
static float render_smp_cmd[60], render_smp_upload[60], render_smp_copy[60];
static float render_smp_swapchain[60], render_smp_renderpass[60], render_smp_submit[60];
static unsigned render_idx_cmd, render_idx_upload, render_idx_copy;
static unsigned render_idx_swapchain, render_idx_renderpass, render_idx_submit;
float render_avg_cmd, render_avg_upload, render_avg_copy;
float render_avg_swapchain, render_avg_renderpass, render_avg_submit;

static void WSDL_WzRender(WSDL_Context* context)
{
	WzDrawList* dl = &context->gui.draw_list;
	SDL_GPUDevice* device = context->gpu_device;

	Uint64 t0 = SDL_GetTicksNS();
	SDL_GPUCommandBuffer* cmd = SDL_AcquireGPUCommandBuffer(device);
	if (!cmd) return;
	render_avg_cmd = perf_avg(render_smp_cmd, &render_idx_cmd, NS_TO_MS(SDL_GetTicksNS() - t0));

	// Upload vertex/index data once per frame
	Uint64 t1 = SDL_GetTicksNS();
	if (dl->vtx_count > 0) {
		void* vtx_map = SDL_MapGPUTransferBuffer(device, context->transfer_vtx, true);
		memcpy(vtx_map, dl->vertices, dl->vtx_count * sizeof(WzVertex));
		SDL_UnmapGPUTransferBuffer(device, context->transfer_vtx);

		void* idx_map = SDL_MapGPUTransferBuffer(device, context->transfer_idx, true);
		memcpy(idx_map, dl->indices, dl->idx_count * sizeof(int));
		SDL_UnmapGPUTransferBuffer(device, context->transfer_idx);
	}
	render_avg_upload = perf_avg(render_smp_upload, &render_idx_upload, NS_TO_MS(SDL_GetTicksNS() - t1));

	Uint64 t2 = SDL_GetTicksNS();
	if (dl->vtx_count > 0) {
		SDL_GPUCopyPass* copy = SDL_BeginGPUCopyPass(cmd);
		SDL_UploadToGPUBuffer(copy,
			&(SDL_GPUTransferBufferLocation){ .transfer_buffer = context->transfer_vtx },
			&(SDL_GPUBufferRegion){ .buffer = context->vertex_buffer, .size = dl->vtx_count * sizeof(WzVertex) },
			true);
		SDL_UploadToGPUBuffer(copy,
			&(SDL_GPUTransferBufferLocation){ .transfer_buffer = context->transfer_idx },
			&(SDL_GPUBufferRegion){ .buffer = context->index_buffer, .size = dl->idx_count * sizeof(int) },
			true);
		SDL_EndGPUCopyPass(copy);
	}
	render_avg_copy = perf_avg(render_smp_copy, &render_idx_copy, NS_TO_MS(SDL_GetTicksNS() - t2));

	// Acquire swapchain texture
	Uint64 t3 = SDL_GetTicksNS();
	SDL_GPUTexture* swapchain_tex = NULL;
	Uint32 sw, sh;
	if (!SDL_AcquireGPUSwapchainTexture(cmd, context->window, &swapchain_tex, &sw, &sh) || !swapchain_tex) {
		SDL_SubmitGPUCommandBuffer(cmd);
		return;
	}
	render_avg_swapchain = perf_avg(render_smp_swapchain, &render_idx_swapchain, NS_TO_MS(SDL_GetTicksNS() - t3));

	Uint64 t4 = SDL_GetTicksNS();
	SDL_GPUColorTargetInfo color_target = {
		.texture = swapchain_tex,
		.load_op = SDL_GPU_LOADOP_CLEAR,
		.store_op = SDL_GPU_STOREOP_STORE,
		.clear_color = { 32.0f / 255.0f, 140.0f / 255.0f, 113.0f / 255.0f, 1.0f },
	};
	SDL_GPURenderPass* pass = SDL_BeginGPURenderPass(cmd, &color_target, 1, NULL);

	if (dl->vtx_count > 0 && dl->draw_call_count > 0) {
		SDL_BindGPUGraphicsPipeline(pass, context->pipeline);
		SDL_GPUBufferBinding vtx_binding = { .buffer = context->vertex_buffer };
		SDL_BindGPUVertexBuffers(pass, 0, &vtx_binding, 1);
		SDL_GPUBufferBinding idx_binding = { .buffer = context->index_buffer };
		SDL_BindGPUIndexBuffer(pass, &idx_binding, SDL_GPU_INDEXELEMENTSIZE_32BIT);

		float uniforms[4] = { (float)sw, (float)sh, 0, 0 };
		SDL_PushGPUVertexUniformData(cmd, 0, uniforms, sizeof(uniforms));

		for (unsigned i = 0; i < dl->draw_call_count; ++i) {
			WzDrawCall* dc = &dl->draw_calls[i];

			if (dc->has_clip) {
				SDL_Rect scissor = { (int)dc->clip_rect.x, (int)dc->clip_rect.y,
					(int)dc->clip_rect.w, (int)dc->clip_rect.h };
				SDL_SetGPUScissor(pass, &scissor);
			} else {
				SDL_Rect scissor = { 0, 0, (int)sw, (int)sh };
				SDL_SetGPUScissor(pass, &scissor);
			}

			SDL_GPUTexture* tex = dc->texture ? (SDL_GPUTexture*)dc->texture : context->white_texture;
			SDL_GPUTextureSamplerBinding sampler_binding = {
				.texture = tex,
				.sampler = context->sampler_nearest,
			};
			SDL_BindGPUFragmentSamplers(pass, 0, &sampler_binding, 1);

			SDL_DrawGPUIndexedPrimitives(pass, dc->idx_count, 1, dc->idx_offset, 0, 0);
		}
	}

	SDL_EndGPURenderPass(pass);
	render_avg_renderpass = perf_avg(render_smp_renderpass, &render_idx_renderpass, NS_TO_MS(SDL_GetTicksNS() - t4));

	Uint64 t5 = SDL_GetTicksNS();
	SDL_SubmitGPUCommandBuffer(cmd);
	render_avg_submit = perf_avg(render_smp_submit, &render_idx_submit, NS_TO_MS(SDL_GetTicksNS() - t5));
}

void WSDL_HandleInput()
{
	for (unsigned i = 0; i < 512; ++i)
	{
		if (wsdl.keyboard.keys[i] == WZ_ACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_ACTIVE;
		}
		if (wsdl.keyboard.keys[i] == WZ_DEACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_INACTIVE;
		}
	}

	int num_keys = 0;
	bool* keys = SDL_GetKeyboardState(&num_keys);
	for (unsigned i = 0; i < num_keys; ++i)
	{
		WZ_Keycode keycode = wz_sdl_scancode_to_keycode(i, 0);
		{
			if (keys[i])
			{
				if (wsdl.keyboard.keys[keycode] == WZ_INACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_ACTIVATING;
				}
			}
			else
			{
				if (wsdl.keyboard.keys[keycode] == WZ_ACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_DEACTIVATING;
				}
			}
		}
	}

}

static int WSDL_TranslateToWzKeycodes(SDL_Scancode scancode) {
	// Handle ASCII range (a-z, 0-9, punctuation, etc.)
	// SDL scancodes for letters are offset from ASCII
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		return 'a' + (scancode - SDL_SCANCODE_A);  // Map to lowercase ASCII
	}

	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) return '0';


	// Special ASCII characters
	switch (scancode) {
	case SDL_SCANCODE_SPACE: return ' ';
	case SDL_SCANCODE_RETURN: return '\n';
	case SDL_SCANCODE_TAB: return '\t';
	case SDL_SCANCODE_BACKSPACE: return '\b';
	case SDL_SCANCODE_ESCAPE: return 27;  // ESC

		// Punctuation (you may need to adjust these based on your keyboard layout)
	case SDL_SCANCODE_MINUS: return '-';
	case SDL_SCANCODE_EQUALS: return '=';
	case SDL_SCANCODE_LEFTBRACKET: return '[';
	case SDL_SCANCODE_RIGHTBRACKET: return ']';
	case SDL_SCANCODE_BACKSLASH: return '\\';
	case SDL_SCANCODE_SEMICOLON: return ';';
	case SDL_SCANCODE_APOSTROPHE: return '\'';
	case SDL_SCANCODE_GRAVE: return '`';
	case SDL_SCANCODE_COMMA: return ',';
	case SDL_SCANCODE_PERIOD: return '.';
	case SDL_SCANCODE_SLASH: return '/';
	}

	// Extended keys (>= 128)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK: return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1: return WZ_KEY_F1;
	case SDL_SCANCODE_F2: return WZ_KEY_F2;
	case SDL_SCANCODE_F3: return WZ_KEY_F3;
	case SDL_SCANCODE_F4: return WZ_KEY_F4;
	case SDL_SCANCODE_F5: return WZ_KEY_F5;
	case SDL_SCANCODE_F6: return WZ_KEY_F6;
	case SDL_SCANCODE_F7: return WZ_KEY_F7;
	case SDL_SCANCODE_F8: return WZ_KEY_F8;
	case SDL_SCANCODE_F9: return WZ_KEY_F9;
	case SDL_SCANCODE_F10: return WZ_KEY_F10;
	case SDL_SCANCODE_F11: return WZ_KEY_F11;
	case SDL_SCANCODE_F12: return WZ_KEY_F12;
	case SDL_SCANCODE_PRINTSCREEN: return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK: return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE: return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT: return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME: return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP: return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE: return WZ_KEY_DELETE;
	case SDL_SCANCODE_END: return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN: return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT: return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT: return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN: return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP: return WZ_KEY_UP;
	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE: return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY: return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS: return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS: return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER: return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1: return WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2: return WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3: return WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4: return WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5: return WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6: return WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7: return WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8: return WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9: return WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0: return WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD: return WZ_KEY_KP_PERIOD;
	case SDL_SCANCODE_APPLICATION: return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER: return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS: return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13: return WZ_KEY_F13;
	case SDL_SCANCODE_F14: return WZ_KEY_F14;
	case SDL_SCANCODE_F15: return WZ_KEY_F15;
	case SDL_SCANCODE_F16: return WZ_KEY_F16;
	case SDL_SCANCODE_F17: return WZ_KEY_F17;
	case SDL_SCANCODE_F18: return WZ_KEY_F18;
	case SDL_SCANCODE_F19: return WZ_KEY_F19;
	case SDL_SCANCODE_F20: return WZ_KEY_F20;
	case SDL_SCANCODE_F21: return WZ_KEY_F21;
	case SDL_SCANCODE_F22: return WZ_KEY_F22;
	case SDL_SCANCODE_F23: return WZ_KEY_F23;
	case SDL_SCANCODE_F24: return WZ_KEY_F24;
	case SDL_SCANCODE_EXECUTE: return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP: return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU: return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT: return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP: return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN: return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO: return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT: return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY: return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE: return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND: return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE: return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP: return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN: return WZ_KEY_VOLUMEDOWN;
	case SDL_SCANCODE_LCTRL: return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT: return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT: return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI: return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL: return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT: return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT: return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI: return WZ_KEY_RGUI;
	case SDL_SCANCODE_MODE: return WZ_KEY_MODE;

	default: return WZ_KEY_UNKNOWN;
	}
}

SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
	WzEvent wz_event = { 0 };

	switch (event->type) {
	case SDL_EVENT_KEY_DOWN: {
		unsigned wz_key = (unsigned)wz_sdl_scancode_to_keycode(event->key.scancode, event->key.mod);
		if (wz_key != WZ_KEY_UNKNOWN) {
			bool is_repeat = (event->key.repeat != 0);
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.key = wz_key,
				.down = true,
				.repeat = is_repeat,
				.mod = sdl_keymod_to_wz(event->key.mod),
			};
		}
		break;
	}

	case SDL_EVENT_KEY_UP: {
		int wz_key = WSDL_TranslateToWzKeycodes(event->key.scancode);
		if (wz_key != WZ_KEY_UNKNOWN) {
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.mod = sdl_keymod_to_wz(event->key.mod),
				.key = wz_key,
			};
		}
		break;
	}

						 // Mouse button events
	case SDL_EVENT_MOUSE_BUTTON_DOWN: {
		wz_input_mouse_button_event(
			event->button.button,
			true,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.down = true,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};
		break;
	}

	case SDL_EVENT_MOUSE_BUTTON_UP: {
		wz_input_mouse_button_event(
			event->button.button,
			false,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};

		break;
	}

	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}

	if (wz_event.type)
	{
		events[events_count++] = wz_event;
		assert(events_count < MAX_NUM_EVENTS);
	}

	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void* appstate)
{
	wz_gui_deinit(&gui);
}

SDL_EnumerationResult SDLCALL onFile(void* userdata, const char* dirname, const char* filename)
{
#if 0
	char path[512];
	sprintf(path, "%s%s", dirname, filename);

	assert(image_widgets_count < MAX_NUM_IMAGE_WIDGETS - 1);
	load_animation(renderer, &image_widgets[image_widgets_count].animation, path);
	image_widgets[image_widgets_count].scale_x = 1;
	image_widgets[image_widgets_count].scale_y = 1;
	image_widgets_count++;
#endif

	return SDL_ENUM_CONTINUE;
}

void load_animations()
{
	bool result = SDL_EnumerateDirectory("Gifs", onFile, 0);
	if (!result)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}
}

void WSDL_ContextCreate(WSDL_Context* context, unsigned window_width, unsigned window_height)
{
	SDL_Window* window = SDL_CreateWindow("my window", window_width, window_height, SDL_WINDOW_RESIZABLE);
	assert(window);

	SDL_GPUDevice* device = SDL_CreateGPUDevice(SDL_GPU_SHADERFORMAT_DXBC, true, NULL);
	assert(device);

	bool claimed = SDL_ClaimWindowForGPUDevice(device, window);
	assert(claimed);

	SDL_SetGPUSwapchainParameters(device, window,
		SDL_GPU_SWAPCHAINCOMPOSITION_SDR, SDL_GPU_PRESENTMODE_IMMEDIATE);

	// Compile shaders
	SDL_GPUShader* vs = compile_hlsl_shader(device, vs_hlsl_source,
		"vs_5_1", SDL_GPU_SHADERSTAGE_VERTEX, 0, 1);
	SDL_GPUShader* ps = compile_hlsl_shader(device, ps_hlsl_source,
		"ps_5_1", SDL_GPU_SHADERSTAGE_FRAGMENT, 1, 0);
	assert(vs && ps);

	SDL_GPUTextureFormat sc_format = SDL_GetGPUSwapchainTextureFormat(device, window);

	SDL_GPUVertexAttribute vertex_attrs[] = {
		{ .location = 0, .buffer_slot = 0, .format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2, .offset = 0  },
		{ .location = 1, .buffer_slot = 0, .format = SDL_GPU_VERTEXELEMENTFORMAT_UINT,   .offset = 8  },
		{ .location = 2, .buffer_slot = 0, .format = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2, .offset = 12 },
	};
	SDL_GPUVertexBufferDescription vbuf_desc = {
		.slot = 0, .pitch = sizeof(WzVertex), .input_rate = SDL_GPU_VERTEXINPUTRATE_VERTEX,
	};

	SDL_GPUColorTargetDescription color_desc = {
		.format = sc_format,
		.blend_state = {
			.enable_blend = true,
			.src_color_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA,
			.dst_color_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
			.color_blend_op = SDL_GPU_BLENDOP_ADD,
			.src_alpha_blendfactor = SDL_GPU_BLENDFACTOR_SRC_ALPHA,
			.dst_alpha_blendfactor = SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
			.alpha_blend_op = SDL_GPU_BLENDOP_ADD,
		},
	};
	SDL_GPUGraphicsPipeline* pipeline = SDL_CreateGPUGraphicsPipeline(device,
		&(SDL_GPUGraphicsPipelineCreateInfo){
			.vertex_shader = vs, .fragment_shader = ps,
			.vertex_input_state = {
				.vertex_buffer_descriptions = &vbuf_desc, .num_vertex_buffers = 1,
				.vertex_attributes = vertex_attrs, .num_vertex_attributes = 3,
			},
			.primitive_type = SDL_GPU_PRIMITIVETYPE_TRIANGLELIST,
			.rasterizer_state = { .fill_mode = SDL_GPU_FILLMODE_FILL, .cull_mode = SDL_GPU_CULLMODE_NONE },
			.multisample_state = { .sample_count = SDL_GPU_SAMPLECOUNT_1 },
			.target_info = { .color_target_descriptions = &color_desc, .num_color_targets = 1 },
		});
	assert(pipeline);

	SDL_ReleaseGPUShader(device, vs);
	SDL_ReleaseGPUShader(device, ps);

	SDL_GPUSampler* sampler_nearest = SDL_CreateGPUSampler(device,
		&(SDL_GPUSamplerCreateInfo){
			.min_filter = SDL_GPU_FILTER_NEAREST, .mag_filter = SDL_GPU_FILTER_NEAREST,
			.mipmap_mode = SDL_GPU_SAMPLERMIPMAPMODE_NEAREST,
			.address_mode_u = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
			.address_mode_v = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
			.address_mode_w = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
		});
	SDL_GPUSampler* sampler_linear = SDL_CreateGPUSampler(device,
		&(SDL_GPUSamplerCreateInfo){
			.min_filter = SDL_GPU_FILTER_LINEAR, .mag_filter = SDL_GPU_FILTER_LINEAR,
			.mipmap_mode = SDL_GPU_SAMPLERMIPMAPMODE_LINEAR,
			.address_mode_u = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
			.address_mode_v = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
			.address_mode_w = SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE,
		});

	SDL_GPUBuffer* vertex_buffer = SDL_CreateGPUBuffer(device,
		&(SDL_GPUBufferCreateInfo){ .usage = SDL_GPU_BUFFERUSAGE_VERTEX, .size = WZ_MAX_VERTICES * sizeof(WzVertex) });
	SDL_GPUBuffer* index_buffer = SDL_CreateGPUBuffer(device,
		&(SDL_GPUBufferCreateInfo){ .usage = SDL_GPU_BUFFERUSAGE_INDEX, .size = WZ_MAX_INDICES * sizeof(int) });

	SDL_GPUTransferBuffer* transfer_vtx = SDL_CreateGPUTransferBuffer(device,
		&(SDL_GPUTransferBufferCreateInfo){ .usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD, .size = WZ_MAX_VERTICES * sizeof(WzVertex) });
	SDL_GPUTransferBuffer* transfer_idx = SDL_CreateGPUTransferBuffer(device,
		&(SDL_GPUTransferBufferCreateInfo){ .usage = SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD, .size = WZ_MAX_INDICES * sizeof(int) });

	unsigned char white_pixel[] = { 255, 255, 255, 255 };
	SDL_GPUTexture* white_texture = gpu_upload_texture(device, white_pixel, 1, 1);

	context->window = window;
	context->gpu_device = device;
	context->pipeline = pipeline;
	context->sampler_nearest = sampler_nearest;
	context->sampler_linear = sampler_linear;
	context->white_texture = white_texture;
	context->vertex_buffer = vertex_buffer;
	context->index_buffer = index_buffer;
	context->transfer_vtx = transfer_vtx;
	context->transfer_idx = transfer_idx;
}

SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
	WSDL_ContextCreate(&gui_window, WINDOW_WIDTH, WINDOW_HEIGHT);

	// Load fonts via wzgui atlas
	wz_set_gui(&gui_window.gui);
	{
		size_t file_size;
		unsigned char* data = (unsigned char*)SDL_LoadFile("C:\\Windows\\Fonts\\Arial.ttf", &file_size);
		if (!data) {
			SDL_Log("Failed to load font: %s", SDL_GetError());
			return SDL_APP_FAILURE;
		}
		wz_font_load(0, data, (unsigned)file_size, 18.0f);
		wz_font_load(1, data, (unsigned)file_size, 28.0f);
		SDL_free(data);

		data = (unsigned char*)SDL_LoadFile("C:\\Windows\\Fonts\\ArialBD.ttf", &file_size);
		if (data) {
			wz_font_load(2, data, (unsigned)file_size, 24.0f);
			SDL_free(data);
		}

		// Pack icons into font 0's atlas before uploading
		wz_create_dropdown_icon();
		wz_pack_icons_into_atlas();

		// Upload atlas textures to GPU
		for (unsigned fi = 0; fi < gui_window.gui.fonts_count; fi++) {
			WzFont* font = &gui_window.gui.fonts[fi];
			SDL_GPUTexture* atlas_tex = gpu_upload_alpha_atlas(gui_window.gpu_device, font->atlas_bitmap, font->atlas_w, font->atlas_h);
			free(font->atlas_bitmap);
			font->atlas_bitmap = NULL;
			wz_font_set_atlas_texture(fi, (WzTexture) { .data = atlas_tex, .w = (float)font->atlas_w, .h = (float)font->atlas_h });
		}

		// Dropdown icon now lives in font 0 atlas (draw code reads atlas UVs directly)
		free(gui_window.gui.dropdown_icon_bitmap);
		gui_window.gui.dropdown_icon_bitmap = NULL;

		// X icon: reference font 0 atlas with sub-region UVs
		{
			WzFont* font = &gui_window.gui.fonts[0];
			gui.x_icon = (WzTexture){
				.data = font->atlas_texture.data,
				.w = 16, .h = 16,
				.src_x = gui_window.gui.x_icon_atlas_x,
				.src_y = gui_window.gui.x_icon_atlas_y,
				.tex_w = (float)font->atlas_w,
				.tex_h = (float)font->atlas_h,
			};
		}
	}

	return SDL_APP_CONTINUE;
}

void WSDL_WindowContextBegin(WSDL_Context* context)
{
	(void)context;
}

void WSDL_WzBegin(WSDL_Context* context)
{
	WSDL_WindowContextBegin(context);
}

bool WSDL_IsInteracting(char k)
{
	bool result = wsdl.keyboard.keys[k] == WZ_ACTIVATING || wsdl.keyboard.keys[k] == WZ_ACTIVE;

	return result;
}

SDL_AppResult SDL_AppIterate(void* appstate)
{
	static float delta_time;

	static float smp_total[60], smp_gui[60], smp_layout[60], smp_sdl[60];
	static unsigned idx_total, idx_gui, idx_layout, idx_sdl;

	Uint64 time_beginning = SDL_GetTicksNS();

	WSDL_WzBegin(&gui_window);
	wz_set_gui(&gui_window.gui);

	gui_window.gui.ticks_in_ns = SDL_GetTicksNS;
	gui_window.gui.ticks_in_ms = SDL_GetTicks;

	Uint64 t_gui_begin = SDL_GetTicksNS();
	WSDL_WzBeginWidgets(&gui_window);
	{
		WzWidget window = (WzWidget){ 0 };
		WzWidget ib_window = wz_vbox_id(window, WIDGET_VBOX1);

		WzStr strs[] = { wz_str_create("wow1"), wz_str_create("wow2"), wz_str_create("wow3") };
		static int selected_text = -1;
		static bool active;
		wz_dropdown(ib_window, strs, 3, &selected_text, &active, WIDGET_DROPDOWN1);
		WzWidget w = wz_label_id(ib_window, wz_str_create("euaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), WIDGET_LABEL1);
	}
	float avg_gui = perf_avg(smp_gui, &idx_gui, NS_TO_MS(SDL_GetTicksNS() - t_gui_begin));

	Uint64 t_layout_begin = SDL_GetTicksNS();
	WSDL_WzEnd(&gui_window);
	float avg_layout = perf_avg(smp_layout, &idx_layout, NS_TO_MS(SDL_GetTicksNS() - t_layout_begin));

	if (gui_window.gui.copied_text[0])
	{
		SDL_SetClipboardText(gui_window.gui.copied_text);
		gui_window.gui.copied_text[0] = '\0';
	}

	int current_window_w, current_window_h;
	SDL_GetWindowSize(gui_window.window, &current_window_w, &current_window_h);

	float avg_total = perf_avg(smp_total, &idx_total, delta_time);

	{
		static float avg_sdl_prev;
		const char* labels[] = {
			"total", "gui", "layout", "sdl", "draws",
			"  cmd", "  upload", "  copy", "  swapchain", "  renderpass", "  submit"
		};
		float avg_values[] = {
			avg_total, avg_gui, avg_layout, avg_sdl_prev, (float)gui_window.gui.draw_list.draw_call_count,
			render_avg_cmd, render_avg_upload, render_avg_copy,
			render_avg_swapchain, render_avg_renderpass, render_avg_submit
		};

		char buf[48];
		float text_h = 0.0f;
		for (int i = 0; i < 11; ++i)
		{
			if (i == 4)
				sprintf(buf, "%s: %d", labels[i], (int)avg_values[i]);
			else
				sprintf(buf, "%s: %.2f ms", labels[i], avg_values[i]);
			float text_w;
			wz_get_text_size(buf, 0, (unsigned)strlen(buf), 2, &text_w, &text_h);
			wz_draw_text(2, (int)(current_window_w - text_w - 8),
				(int)(8 + i * (text_h + 4)), buf, strlen(buf), WZ_YELLOW);
		}

		Uint64 t_sdl_begin = SDL_GetTicksNS();
		WSDL_WzRender(&gui_window);
		avg_sdl_prev = perf_avg(smp_sdl, &idx_sdl, NS_TO_MS(SDL_GetTicksNS() - t_sdl_begin));
	}

	// Cap frame rate
	delta_time = NS_TO_MS(SDL_GetTicksNS() - time_beginning);
	if (delta_time < 16.0f)
		SDL_Delay((Uint64)(16.0f - delta_time));

	return SDL_APP_CONTINUE;
}

