#define SDL_MAIN_USE_CALLBACKS 1  /* use the callbacks instead of main() */

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <SDL3_image/SDL_image.h>
#include <stdio.h>
#include "WzGuiCore.h"
#include "WzLayout_ispc.h"  // generated by: ispc WzLayout.ispc --target=avx2-i32x8 --header-outfile=WzLayout_ispc.h
#define _USE_MATH_DEFINES
#include <math.h>

#define CONCAT(a, b) a##b
#define ITEM(name, num) CONCAT(name, num),

// These must be hard-coded because the preprocessor can't do "offset + 1"
#define GEN_2(n, o0, o1)      ITEM(n, o0) ITEM(n, o1)
#define GEN_4(n, o0, o1, o2, o3) GEN_2(n, o0, o1) GEN_2(n, o2, o3)

// To avoid writing 512 arguments, we use a slightly different "Nested" approach:
#define B000(n, p) ITEM(n, p##0) ITEM(n, p##1) ITEM(n, p##2) ITEM(n, p##3) ITEM(n, p##4) ITEM(n, p##5) ITEM(n, p##6) ITEM(n, p##7)
#define B00(n, p)  B000(n, p##0) B000(n, p##1) B000(n, p##2) B000(n, p##3) B000(n, p##4) B000(n, p##5) B000(n, p##6) B000(n, p##7)

// This will generate items 000 through 511 (formatted as 3 digits to avoid math)
#define GEN_512_SAFE(n) \
    B00(n, 0) B00(n, 1) B00(n, 2) B00(n, 3) B00(n, 4) B00(n, 5) B00(n, 6) B00(n, 7)

enum
{
	WIDGET_INPUT_BOX1,
	WIDGET_INPUT_BOX2,
	WIDGET_INPUT_BOX3,
	GEN_512_SAFE(WIDGET_LABEL_LIST)
};



static void wz_layout_ispc_test(void);
static void wz_layout_draw_test(SDL_Renderer* renderer, WzDrawCommandBuffer* out);
static void WSDL_RenderCommandBuffer(SDL_Renderer* renderer, WzDrawCommandBuffer* buf);

#define MAX_NUM_EVENTS 128
unsigned events_count;
WzEvent events[MAX_NUM_EVENTS];

static unsigned short sdl_keymod_to_wz(SDL_Keymod sdl_mod)
{
	unsigned short wz_mod = WZ_KMOD_NONE;

	if (sdl_mod & SDL_KMOD_LSHIFT) wz_mod |= WZ_KMOD_LSHIFT;
	if (sdl_mod & SDL_KMOD_RSHIFT) wz_mod |= WZ_KMOD_RSHIFT;
	if (sdl_mod & SDL_KMOD_LCTRL)  wz_mod |= WZ_KMOD_LCTRL;
	if (sdl_mod & SDL_KMOD_RCTRL)  wz_mod |= WZ_KMOD_RCTRL;
	if (sdl_mod & SDL_KMOD_LALT)   wz_mod |= WZ_KMOD_LALT;
	if (sdl_mod & SDL_KMOD_RALT)   wz_mod |= WZ_KMOD_RALT;
	if (sdl_mod & SDL_KMOD_LGUI)   wz_mod |= WZ_KMOD_LGUI;
	if (sdl_mod & SDL_KMOD_RGUI)   wz_mod |= WZ_KMOD_RGUI;

	return wz_mod;
}

// Convert SDL3 scancode + modifiers to WZ keycode
// Returns 0-127 for ASCII characters, 128+ for special keys
WZ_Keycode wz_sdl_scancode_to_keycode(SDL_Scancode scancode, SDL_Keymod modifiers)
{
	bool shift = (modifiers & (SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT)) != 0;
	bool caps = (modifiers & SDL_KMOD_CAPS) != 0;

	// Letters A-Z
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		char base = 'a' + (scancode - SDL_SCANCODE_A);
		// Caps lock XOR shift gives uppercase
		if (caps != shift) {
			return base - 32; // Uppercase ASCII
		}
		return base; // Lowercase ASCII
	}

	// Numbers 1-9, 0
	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		if (shift) {
			const char symbols[] = "!@#$%^&*(";
			return symbols[scancode - SDL_SCANCODE_1];
		}
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) {
		return shift ? ')' : '0';
	}

	// Punctuation and special keys (ASCII range)
	switch (scancode) {
	case SDL_SCANCODE_SPACE:      return ' ';
	case SDL_SCANCODE_RETURN:     return '\n';
	case SDL_SCANCODE_ESCAPE:     return 27;
	case SDL_SCANCODE_BACKSPACE:  return '\b';
	case SDL_SCANCODE_TAB:        return '\t';

	case SDL_SCANCODE_MINUS:      return shift ? '_' : '-';
	case SDL_SCANCODE_EQUALS:     return shift ? '+' : '=';
	case SDL_SCANCODE_LEFTBRACKET:  return shift ? '{' : '[';
	case SDL_SCANCODE_RIGHTBRACKET: return shift ? '}' : ']';
	case SDL_SCANCODE_BACKSLASH:    return shift ? '|' : '\\';
	case SDL_SCANCODE_SEMICOLON:    return shift ? ':' : ';';
	case SDL_SCANCODE_APOSTROPHE:   return shift ? '"' : '\'';
	case SDL_SCANCODE_GRAVE:        return shift ? '~' : '`';
	case SDL_SCANCODE_COMMA:        return shift ? '<' : ',';
	case SDL_SCANCODE_PERIOD:       return shift ? '>' : '.';
	case SDL_SCANCODE_SLASH:        return shift ? '?' : '/';
	}

	// Extended keys (128+)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK:     return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1:           return WZ_KEY_F1;
	case SDL_SCANCODE_F2:           return WZ_KEY_F2;
	case SDL_SCANCODE_F3:           return WZ_KEY_F3;
	case SDL_SCANCODE_F4:           return WZ_KEY_F4;
	case SDL_SCANCODE_F5:           return WZ_KEY_F5;
	case SDL_SCANCODE_F6:           return WZ_KEY_F6;
	case SDL_SCANCODE_F7:           return WZ_KEY_F7;
	case SDL_SCANCODE_F8:           return WZ_KEY_F8;
	case SDL_SCANCODE_F9:           return WZ_KEY_F9;
	case SDL_SCANCODE_F10:          return WZ_KEY_F10;
	case SDL_SCANCODE_F11:          return WZ_KEY_F11;
	case SDL_SCANCODE_F12:          return WZ_KEY_F12;

	case SDL_SCANCODE_PRINTSCREEN:  return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK:   return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE:        return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT:       return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME:         return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP:       return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE:       return WZ_KEY_DELETE;
	case SDL_SCANCODE_END:          return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN:     return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT:        return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT:         return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN:         return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP:           return WZ_KEY_UP;

	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE:    return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY:  return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS:     return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS:      return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER:     return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1:         return (modifiers & SDL_KMOD_NUM) ? '1' : WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2:         return (modifiers & SDL_KMOD_NUM) ? '2' : WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3:         return (modifiers & SDL_KMOD_NUM) ? '3' : WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4:         return (modifiers & SDL_KMOD_NUM) ? '4' : WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5:         return (modifiers & SDL_KMOD_NUM) ? '5' : WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6:         return (modifiers & SDL_KMOD_NUM) ? '6' : WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7:         return (modifiers & SDL_KMOD_NUM) ? '7' : WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8:         return (modifiers & SDL_KMOD_NUM) ? '8' : WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9:         return (modifiers & SDL_KMOD_NUM) ? '9' : WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0:         return (modifiers & SDL_KMOD_NUM) ? '0' : WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD:    return (modifiers & SDL_KMOD_NUM) ? '.' : WZ_KEY_KP_PERIOD;

	case SDL_SCANCODE_APPLICATION:  return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER:        return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS:    return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13:          return WZ_KEY_F13;
	case SDL_SCANCODE_F14:          return WZ_KEY_F14;
	case SDL_SCANCODE_F15:          return WZ_KEY_F15;
	case SDL_SCANCODE_F16:          return WZ_KEY_F16;
	case SDL_SCANCODE_F17:          return WZ_KEY_F17;
	case SDL_SCANCODE_F18:          return WZ_KEY_F18;
	case SDL_SCANCODE_F19:          return WZ_KEY_F19;
	case SDL_SCANCODE_F20:          return WZ_KEY_F20;
	case SDL_SCANCODE_F21:          return WZ_KEY_F21;
	case SDL_SCANCODE_F22:          return WZ_KEY_F22;
	case SDL_SCANCODE_F23:          return WZ_KEY_F23;
	case SDL_SCANCODE_F24:          return WZ_KEY_F24;

	case SDL_SCANCODE_EXECUTE:      return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP:         return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU:         return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT:       return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP:         return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN:        return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO:         return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT:          return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY:         return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE:        return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND:         return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE:         return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP:     return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN:   return WZ_KEY_VOLUMEDOWN;

	case SDL_SCANCODE_LCTRL:        return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT:       return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT:         return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI:         return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL:        return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT:       return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT:         return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI:         return WZ_KEY_RGUI;

	case SDL_SCANCODE_MODE:         return WZ_KEY_MODE;

	default:
		return WZ_KEY_UNKNOWN;
	}
}

// Helper: Check if keycode is printable ASCII
bool wz_keycode_is_printable(WZ_Keycode keycode)
{
	return keycode >= 32 && keycode <= 126;
}

// Helper: Check if keycode is ASCII (printable or control)
bool wz_keycode_is_ascii(WZ_Keycode keycode)
{
	return keycode >= 0 && keycode < 128;
}

// Helper: Check if keycode is extended (special key)
bool wz_keycode_is_extended(WZ_Keycode keycode)
{
	return keycode >= 128 && keycode < WZ_KEY_COUNT;
}

// Upload a single-channel alpha bitmap to an RGBA SDL_Texture for font atlas rendering
static SDL_Texture* wz_upload_font_atlas_rt(SDL_Renderer* renderer, const unsigned char* bitmap, int w, int h)
{
	SDL_Texture* tex = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ABGR8888, SDL_TEXTUREACCESS_STATIC, w, h);
	assert(tex);
	unsigned char* rgba = (unsigned char*)malloc(w * h * 4);
	for (int i = 0; i < w * h; i++) {
		rgba[i * 4 + 0] = 255;
		rgba[i * 4 + 1] = 255;
		rgba[i * 4 + 2] = 255;
		rgba[i * 4 + 3] = bitmap[i];
	}
	SDL_UpdateTexture(tex, NULL, rgba, w * 4);
	free(rgba);
	SDL_SetTextureBlendMode(tex, SDL_BLENDMODE_BLEND);
	SDL_SetTextureScaleMode(tex, SDL_SCALEMODE_NEAREST);
	return tex;
}

typedef struct Wsdl
{
	WzKeyboard keyboard;
} Wsdl;

Wsdl wsdl;

typedef struct
{
	SDL_Window* window;
	SDL_Renderer* renderer;
	TTF_TextEngine* text_engine;
	WzGui gui;
} WSDL_Context;

WSDL_Context main_window;
WSDL_Context gui_window;

SDL_Texture* x_icon_texture;


// Color component extraction macros (for RGBA format: 0xRRGGBBAA)
#define WZ_COLOR_R(c) (((c) >> 24) & 0xFF)
#define WZ_COLOR_G(c) (((c) >> 16) & 0xFF)
#define WZ_COLOR_B(c) (((c) >> 8) & 0xFF)
#define WZ_COLOR_A(c) ((c) & 0xFF)
#define WZ_RGBA(r,g,b,a) (((unsigned)(r)<<24)|((unsigned)(g)<<16)|((unsigned)(b)<<8)|(unsigned)(a))

static WzDrawCommandBuffer ispc_cmds;

static void wz_push_filled_rect(WzDrawCommandBuffer* buf, float x, float y, float w, float h, unsigned color)
{
	if (!buf || buf->count >= MAX_NUM_DRAW_COMMANDS - 1) return;
	WzDrawCommand* cmd = &buf->commands[buf->count++];
	cmd->type = DrawCommandType_Rect;
	cmd->x = x; cmd->y = y; cmd->w = w; cmd->h = h; cmd->color = color;
}

static void wz_ispc_push_rect(WzDrawCommandBuffer* buf, const struct WzSlotOld* slot, int lane, unsigned color)
{
	wz_push_filled_rect(buf, slot->abs_x[lane], slot->abs_y[lane], slot->abs_width[lane], slot->abs_height[lane], color);
}

//#define assert(x) void(x)

#define MAX_NUM_TEXTURES_IN_ANIMATION 128

typedef struct Animation
{
	SDL_Texture* textures[MAX_NUM_TEXTURES_IN_ANIMATION];
	unsigned textures_count;
	unsigned w, h;
} Animation;

typedef struct WzWidgetPersistentData
{
	WzWidget widget;
	float transform_x, transform_y;
	float scale_x, scale_y;
	float rotation;

	Animation animation;
	unsigned current_animation_frame;
} WzWidgetPersistentData;

#define MAX_NUM_IMAGE_WIDGETS 32
WzWidgetPersistentData image_widgets[MAX_NUM_IMAGE_WIDGETS];
unsigned image_widgets_count;

WzGui gui;

WzTexture texture;

#define MAX_NUM_RENDERERS 16
#define MAX_NUM_WINDOWS 16


WzState left_mouse;

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 540

bool error;



bool load_animation(SDL_Renderer* renderer, Animation* animation, const char* path)
{
	bool success = true;
	IMG_Animation* anim = IMG_LoadAnimation(path);

	if (!anim)
	{
		return false;
	}

	if (anim->count == MAX_NUM_TEXTURES_IN_ANIMATION)
	{
		SDL_SetError("Loaded to many gifs");
		return false;
	}

	*animation = (Animation){ .textures_count = anim->count, .w = anim->w, .h = anim->h };
	for (int i = 0; i < anim->count; i++)
	{
		animation->textures[i] = SDL_CreateTextureFromSurface(renderer, anim->frames[i]);
		if (!animation->textures[i])
		{
			return false;
		}
	}
}

static void WSDL_RenderCommandBuffer(SDL_Renderer* renderer, WzDrawCommandBuffer* buf)
{
	for (int i = 0; i < buf->count; ++i)
	{
		WzDrawCommand command = buf->commands[i];
		if (command.type == DrawCommandType_Rect)
		{
			SDL_SetRenderDrawColor(renderer,
				WZ_COLOR_R(command.color), WZ_COLOR_G(command.color),
				WZ_COLOR_B(command.color), WZ_COLOR_A(command.color));
			SDL_FRect rect = { command.x, command.y, command.w, command.h };
			SDL_RenderFillRect(renderer, &rect);
		}
	}
}

static void WSDL_WzBeginWidgets(WSDL_Context* context)
{

	Uint32 flags = SDL_GetWindowFlags(context->window);
	float mouse_x = 0, mouse_y = 0;
	if (flags & SDL_WINDOW_MOUSE_FOCUS)
	{
		SDL_GetMouseState(&mouse_x, &mouse_y);
	}

	context->gui.mouse_pos.x = mouse_x;
	context->gui.mouse_pos.y = mouse_y;
#if 0

	// Mouse Input
	{
		float mx, my;
		Uint32 mflags = SDL_GetMouseState(&mx, &my);
		printf("%u\n", mflags);

		if (left_mouse == WZ_ACTIVATING)
		{
			left_mouse = WZ_ACTIVE;
		}
		else if (left_mouse == WZ_DEACTIVATING)
		{
			left_mouse = WZ_INACTIVE;
		}

		if (mflags & SDL_BUTTON_LMASK)
		{
			if (left_mouse == WZ_INACTIVE)
			{
				left_mouse = WZ_ACTIVATING;
			}
		}
		else
		{
			if (left_mouse == WZ_ACTIVE)
			{
				left_mouse = WZ_DEACTIVATING;
			}
		}
	}
#endif
	wz_begin(WINDOW_WIDTH, WINDOW_HEIGHT,
		events, events_count, true);
}

void WSDL_WzEnd(WSDL_Context* context)
{
	wz_end();

	SDL_Renderer* renderer = context->renderer;
	WzDrawList* dl = &context->gui.draw_list;

	if (dl->vtx_count == 0) return;

	// WzVertex layout matches SDL_Vertex exactly: {float x,y}, {float r,g,b,a}, {float u,v}
	SDL_Vertex* sdl_verts = (SDL_Vertex*)dl->vertices;

	for (unsigned i = 0; i < dl->draw_call_count; ++i)
	{
		WzDrawCall* dc = &dl->draw_calls[i];

		if (dc->has_clip) {
			SDL_Rect clip = { (int)dc->clip_rect.x, (int)dc->clip_rect.y,
				(int)dc->clip_rect.w, (int)dc->clip_rect.h };
			SDL_SetRenderClipRect(renderer, &clip);
		} else {
			SDL_SetRenderClipRect(renderer, NULL);
		}

		SDL_RenderGeometry(renderer, (SDL_Texture*)dc->texture,
			sdl_verts, (int)dl->vtx_count,
			dl->indices + dc->idx_offset, (int)dc->idx_count);
	}

	SDL_SetRenderClipRect(renderer, NULL);
}

void WSDL_HandleInput()
{
	for (unsigned i = 0; i < 512; ++i)
	{
		if (wsdl.keyboard.keys[i] == WZ_ACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_ACTIVE;
		}
		if (wsdl.keyboard.keys[i] == WZ_DEACTIVATING)
		{
			wsdl.keyboard.keys[i] = WZ_INACTIVE;
		}
	}

	int num_keys = 0;
	bool* keys = SDL_GetKeyboardState(&num_keys);
	for (unsigned i = 0; i < num_keys; ++i)
	{
		WZ_Keycode keycode = wz_sdl_scancode_to_keycode(i, 0);
		{
			if (keys[i])
			{
				if (wsdl.keyboard.keys[keycode] == WZ_INACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_ACTIVATING;
				}
			}
			else
			{
				if (wsdl.keyboard.keys[keycode] == WZ_ACTIVE)
				{
					wsdl.keyboard.keys[keycode] = WZ_DEACTIVATING;
				}
			}
		}
	}

}

static int WSDL_TranslateToWzKeycodes(SDL_Scancode scancode) {
	// Handle ASCII range (a-z, 0-9, punctuation, etc.)
	// SDL scancodes for letters are offset from ASCII
	if (scancode >= SDL_SCANCODE_A && scancode <= SDL_SCANCODE_Z) {
		return 'a' + (scancode - SDL_SCANCODE_A);  // Map to lowercase ASCII
	}

	if (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_9) {
		return '1' + (scancode - SDL_SCANCODE_1);
	}

	if (scancode == SDL_SCANCODE_0) return '0';


	// Special ASCII characters
	switch (scancode) {
	case SDL_SCANCODE_SPACE: return ' ';
	case SDL_SCANCODE_RETURN: return '\n';
	case SDL_SCANCODE_TAB: return '\t';
	case SDL_SCANCODE_BACKSPACE: return '\b';
	case SDL_SCANCODE_ESCAPE: return 27;  // ESC

		// Punctuation (you may need to adjust these based on your keyboard layout)
	case SDL_SCANCODE_MINUS: return '-';
	case SDL_SCANCODE_EQUALS: return '=';
	case SDL_SCANCODE_LEFTBRACKET: return '[';
	case SDL_SCANCODE_RIGHTBRACKET: return ']';
	case SDL_SCANCODE_BACKSLASH: return '\\';
	case SDL_SCANCODE_SEMICOLON: return ';';
	case SDL_SCANCODE_APOSTROPHE: return '\'';
	case SDL_SCANCODE_GRAVE: return '`';
	case SDL_SCANCODE_COMMA: return ',';
	case SDL_SCANCODE_PERIOD: return '.';
	case SDL_SCANCODE_SLASH: return '/';
	}

	// Extended keys (>= 128)
	switch (scancode) {
	case SDL_SCANCODE_CAPSLOCK: return WZ_KEY_CAPSLOCK;
	case SDL_SCANCODE_F1: return WZ_KEY_F1;
	case SDL_SCANCODE_F2: return WZ_KEY_F2;
	case SDL_SCANCODE_F3: return WZ_KEY_F3;
	case SDL_SCANCODE_F4: return WZ_KEY_F4;
	case SDL_SCANCODE_F5: return WZ_KEY_F5;
	case SDL_SCANCODE_F6: return WZ_KEY_F6;
	case SDL_SCANCODE_F7: return WZ_KEY_F7;
	case SDL_SCANCODE_F8: return WZ_KEY_F8;
	case SDL_SCANCODE_F9: return WZ_KEY_F9;
	case SDL_SCANCODE_F10: return WZ_KEY_F10;
	case SDL_SCANCODE_F11: return WZ_KEY_F11;
	case SDL_SCANCODE_F12: return WZ_KEY_F12;
	case SDL_SCANCODE_PRINTSCREEN: return WZ_KEY_PRINTSCREEN;
	case SDL_SCANCODE_SCROLLLOCK: return WZ_KEY_SCROLLLOCK;
	case SDL_SCANCODE_PAUSE: return WZ_KEY_PAUSE;
	case SDL_SCANCODE_INSERT: return WZ_KEY_INSERT;
	case SDL_SCANCODE_HOME: return WZ_KEY_HOME;
	case SDL_SCANCODE_PAGEUP: return WZ_KEY_PAGEUP;
	case SDL_SCANCODE_DELETE: return WZ_KEY_DELETE;
	case SDL_SCANCODE_END: return WZ_KEY_END;
	case SDL_SCANCODE_PAGEDOWN: return WZ_KEY_PAGEDOWN;
	case SDL_SCANCODE_RIGHT: return WZ_KEY_RIGHT;
	case SDL_SCANCODE_LEFT: return WZ_KEY_LEFT;
	case SDL_SCANCODE_DOWN: return WZ_KEY_DOWN;
	case SDL_SCANCODE_UP: return WZ_KEY_UP;
	case SDL_SCANCODE_NUMLOCKCLEAR: return WZ_KEY_NUMLOCKCLEAR;
	case SDL_SCANCODE_KP_DIVIDE: return WZ_KEY_KP_DIVIDE;
	case SDL_SCANCODE_KP_MULTIPLY: return WZ_KEY_KP_MULTIPLY;
	case SDL_SCANCODE_KP_MINUS: return WZ_KEY_KP_MINUS;
	case SDL_SCANCODE_KP_PLUS: return WZ_KEY_KP_PLUS;
	case SDL_SCANCODE_KP_ENTER: return WZ_KEY_KP_ENTER;
	case SDL_SCANCODE_KP_1: return WZ_KEY_KP_1;
	case SDL_SCANCODE_KP_2: return WZ_KEY_KP_2;
	case SDL_SCANCODE_KP_3: return WZ_KEY_KP_3;
	case SDL_SCANCODE_KP_4: return WZ_KEY_KP_4;
	case SDL_SCANCODE_KP_5: return WZ_KEY_KP_5;
	case SDL_SCANCODE_KP_6: return WZ_KEY_KP_6;
	case SDL_SCANCODE_KP_7: return WZ_KEY_KP_7;
	case SDL_SCANCODE_KP_8: return WZ_KEY_KP_8;
	case SDL_SCANCODE_KP_9: return WZ_KEY_KP_9;
	case SDL_SCANCODE_KP_0: return WZ_KEY_KP_0;
	case SDL_SCANCODE_KP_PERIOD: return WZ_KEY_KP_PERIOD;
	case SDL_SCANCODE_APPLICATION: return WZ_KEY_APPLICATION;
	case SDL_SCANCODE_POWER: return WZ_KEY_POWER;
	case SDL_SCANCODE_KP_EQUALS: return WZ_KEY_KP_EQUALS;
	case SDL_SCANCODE_F13: return WZ_KEY_F13;
	case SDL_SCANCODE_F14: return WZ_KEY_F14;
	case SDL_SCANCODE_F15: return WZ_KEY_F15;
	case SDL_SCANCODE_F16: return WZ_KEY_F16;
	case SDL_SCANCODE_F17: return WZ_KEY_F17;
	case SDL_SCANCODE_F18: return WZ_KEY_F18;
	case SDL_SCANCODE_F19: return WZ_KEY_F19;
	case SDL_SCANCODE_F20: return WZ_KEY_F20;
	case SDL_SCANCODE_F21: return WZ_KEY_F21;
	case SDL_SCANCODE_F22: return WZ_KEY_F22;
	case SDL_SCANCODE_F23: return WZ_KEY_F23;
	case SDL_SCANCODE_F24: return WZ_KEY_F24;
	case SDL_SCANCODE_EXECUTE: return WZ_KEY_EXECUTE;
	case SDL_SCANCODE_HELP: return WZ_KEY_HELP;
	case SDL_SCANCODE_MENU: return WZ_KEY_MENU;
	case SDL_SCANCODE_SELECT: return WZ_KEY_SELECT;
	case SDL_SCANCODE_STOP: return WZ_KEY_STOP;
	case SDL_SCANCODE_AGAIN: return WZ_KEY_AGAIN;
	case SDL_SCANCODE_UNDO: return WZ_KEY_UNDO;
	case SDL_SCANCODE_CUT: return WZ_KEY_CUT;
	case SDL_SCANCODE_COPY: return WZ_KEY_COPY;
	case SDL_SCANCODE_PASTE: return WZ_KEY_PASTE;
	case SDL_SCANCODE_FIND: return WZ_KEY_FIND;
	case SDL_SCANCODE_MUTE: return WZ_KEY_MUTE;
	case SDL_SCANCODE_VOLUMEUP: return WZ_KEY_VOLUMEUP;
	case SDL_SCANCODE_VOLUMEDOWN: return WZ_KEY_VOLUMEDOWN;
	case SDL_SCANCODE_LCTRL: return WZ_KEY_LCTRL;
	case SDL_SCANCODE_LSHIFT: return WZ_KEY_LSHIFT;
	case SDL_SCANCODE_LALT: return WZ_KEY_LALT;
	case SDL_SCANCODE_LGUI: return WZ_KEY_LGUI;
	case SDL_SCANCODE_RCTRL: return WZ_KEY_RCTRL;
	case SDL_SCANCODE_RSHIFT: return WZ_KEY_RSHIFT;
	case SDL_SCANCODE_RALT: return WZ_KEY_RALT;
	case SDL_SCANCODE_RGUI: return WZ_KEY_RGUI;
	case SDL_SCANCODE_MODE: return WZ_KEY_MODE;

	default: return WZ_KEY_UNKNOWN;
	}
}

SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
	WzEvent wz_event = { 0 };

	switch (event->type) {
	case SDL_EVENT_KEY_DOWN: {
		unsigned wz_key = (unsigned)wz_sdl_scancode_to_keycode(event->key.scancode, event->key.mod);
		if (wz_key != WZ_KEY_UNKNOWN) {
			bool is_repeat = (event->key.repeat != 0);
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.key = wz_key,
				.down = true,
				.repeat = is_repeat,
				.mod = sdl_keymod_to_wz(event->key.mod),
			};
		}
		break;
	}

	case SDL_EVENT_KEY_UP: {
		int wz_key = WSDL_TranslateToWzKeycodes(event->key.scancode);
		if (wz_key != WZ_KEY_UNKNOWN) {
			wz_event.key = (WzKeyboardEvent)
			{
				.type = WZ_EVENT_TYPE_KEYBOARD,
				.mod = sdl_keymod_to_wz(event->key.mod),
				.key = wz_key,
			};
		}
		break;
	}

						 // Mouse button events
	case SDL_EVENT_MOUSE_BUTTON_DOWN: {
		wz_input_mouse_button_event(
			event->button.button,
			true,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.down = true,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};
		break;
	}

	case SDL_EVENT_MOUSE_BUTTON_UP: {
		wz_input_mouse_button_event(
			event->button.button,
			false,
			event->button.x,
			event->button.y
		);

		wz_event.button = (WzButtonEvent)
		{
			.button = event->button.button,
			.x = event->button.x,
			.y = event->button.y,
			.type = WZ_EVENT_TYPE_MOUSE,
		};

		break;
	}

	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}

	if (wz_event.type)
	{
		events[events_count++] = wz_event;
		assert(events_count < MAX_NUM_EVENTS);
	}

	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void* appstate)
{
	wz_gui_deinit(&gui);
}

SDL_EnumerationResult SDLCALL onFile(void* userdata, const char* dirname, const char* filename)
{
#if 0
	char path[512];
	sprintf(path, "%s%s", dirname, filename);

	assert(image_widgets_count < MAX_NUM_IMAGE_WIDGETS - 1);
	load_animation(renderer, &image_widgets[image_widgets_count].animation, path);
	image_widgets[image_widgets_count].scale_x = 1;
	image_widgets[image_widgets_count].scale_y = 1;
	image_widgets_count++;
#endif

	return SDL_ENUM_CONTINUE;
}

void load_animations()
{
	bool result = SDL_EnumerateDirectory("Gifs", onFile, 0);
	if (!result)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}
}

void WSDL_ContextCreate(WSDL_Context* context, unsigned window_width, unsigned window_height)
{
	bool success = true;
	SDL_Renderer* renderer;
	SDL_Window* window;
	TTF_TextEngine* text_engine;

	success &= SDL_SetHint(SDL_HINT_RENDER_DRIVER, "direct3d");

	success &= SDL_CreateWindowAndRenderer("my window", window_width, window_height,
		SDL_WINDOW_RESIZABLE, &window, &renderer);

	success &= SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);

	text_engine = TTF_CreateRendererTextEngine(renderer);
	success &= (bool)text_engine;

	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);
	}

	context->renderer = renderer;
	context->window = window;
	context->text_engine = text_engine;
}

SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
	bool success = false;

	WSDL_ContextCreate(&gui_window, WINDOW_WIDTH, WINDOW_HEIGHT);

	// Load fonts via wzgui atlas
	wz_set_gui(&gui_window.gui);
	{
		// Font 0: Arial 18px (default)
		size_t file_size;
		unsigned char* data = (unsigned char*)SDL_LoadFile("C:\\Windows\\Fonts\\Arial.ttf", &file_size);
		if (!data) {
			SDL_Log("Failed to load font: %s", SDL_GetError());
			SDL_Quit();
			return 1;
		}
		wz_font_load(0, data, (unsigned)file_size, 18.0f);

		// Font 1: Arial 28px (reuse same ttf data)
		wz_font_load(1, data, (unsigned)file_size, 28.0f);
		SDL_free(data);

		// Upload atlas textures
		for (unsigned fi = 0; fi < gui_window.gui.fonts_count; fi++) {
			WzFont* font = &gui_window.gui.fonts[fi];
			SDL_Texture* atlas_tex = wz_upload_font_atlas_rt(gui_window.renderer, font->atlas_bitmap, font->atlas_w, font->atlas_h);
			free(font->atlas_bitmap);
			font->atlas_bitmap = NULL;
			wz_font_set_atlas_texture(fi, (WzTexture){ .data = atlas_tex, .w = (float)font->atlas_w, .h = (float)font->atlas_h });
		}

	}

	// X icon
	{
		// TODO: Remove width and height fields of wz texture
		SDL_Surface* surface = SDL_CreateSurfaceFrom(16, 16, SDL_PIXELFORMAT_RGBA8888, wz_x_icon, 16 * 4);
		success |= (bool)surface;
		gui.x_icon = (WzTexture){ .w = surface->w, .h = surface->h, .data = SDL_CreateTextureFromSurface(gui_window.renderer, surface) };
	}


	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}

	load_animations();

	//wz_layout_ispc_test();

	return SDL_APP_CONTINUE;
}

void WSDL_WindowContextBegin(WSDL_Context* context)
{
	bool success = true;
	success &= SDL_SetRenderDrawColor(context->renderer, 0x20, 0x8c, 0x71, 255);
	success &= SDL_RenderClear(context->renderer);
}

WzWidget WSDL_WzBegin(WSDL_Context* context)
{
	int window_width, window_height;
	SDL_GetWindowSize(context->window, &window_width, &window_height);

	WSDL_WindowContextBegin(&gui_window);
}

bool WSDL_IsInteracting(char k)
{
	bool result = wsdl.keyboard.keys[k] == WZ_ACTIVATING || wsdl.keyboard.keys[k] == WZ_ACTIVE;

	return result;
}

SDL_AppResult SDL_AppIterate(void* appstate)
{
	unsigned time_beginning = SDL_GetTicks();

	bool success = true;

	ispc_cmds.count = 0;

	WSDL_WzBegin(&gui_window);
	wz_set_gui(&gui_window.gui);

	gui_window.gui.ticks_in_ns = SDL_GetTicksNS;
	gui_window.gui.ticks_in_ms = SDL_GetTicks;

	WSDL_WzBeginWidgets(&gui_window);

	WzWidget window = (WzWidget){ 0 };
	WzWidget ib_window = wz_vbox(window);

	WzStr strs[] = { wz_str_create("wow1"), wz_str_create("wow2"), wz_str_create("wow3") };
	static int selected_text = -1;
	static bool active;
	wz_dropdown(ib_window, strs, 3, &selected_text, &active);
	wz_label(ib_window, wz_str_create("euaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"));

	WSDL_WzEnd(&gui_window);

	if (gui_window.gui.copied_text[0])
	{
		SDL_SetClipboardText(gui_window.gui.copied_text);
		gui_window.gui.copied_text[0] = '\0';
	}

	SDL_SetRenderDrawBlendMode(gui_window.renderer, SDL_BLENDMODE_BLEND);
	WSDL_RenderCommandBuffer(gui_window.renderer, &ispc_cmds);
	SDL_RenderPresent(gui_window.renderer);

	unsigned delta_time = SDL_GetTicks() - time_beginning;
	if (delta_time < 42)
	{
		SDL_Delay(42 - delta_time);
	}

	if (!success)
	{
		SDL_ShowSimpleMessageBox(
			SDL_MESSAGEBOX_ERROR,
			"Fatal Error",
			SDL_GetError(),
			NULL
		);

		return SDL_APP_FAILURE;
	}

	events_count = 0;

	return SDL_APP_CONTINUE;
}

