//
// C:\Users\Elior\source\repos\AdventureWizard\Runtime\WzLayout_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>


#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_WzChunk__
#define __ISPC_STRUCT_WzChunk__
struct WzChunk {
    float pad_left;
    float pad_right;
    float pad_top;
    float pad_bottom;
    float border_left;
    float border_right;
    float border_top;
    float border_bottom;
    float child_gap;
    float min_width;
    float min_height;
    float flex_total;
    float inner_width;
    float inner_height;
    float cursor_x;
    float cursor_y;
    int32_t shrink_width;
    int32_t shrink_height;
    uint32_t child_count;
    uint32_t parent_chunk;
    uint32_t parent_slot;
    int32_t is_horizontal;
    float total_children_min_width;
    float total_children_min_height;
    float w_per_flex_cache;
    float h_per_flex_cache;
    int32_t total_child_count;
    int32_t is_continuation;
    int32_t overflow_group_head;
};
#endif

#ifndef __ISPC_STRUCT_WzSlot__
#define __ISPC_STRUCT_WzSlot__
struct WzSlot {
    float min_width[8];
    float min_height[8];
    float flex[8];
    float margin_left[8];
    float margin_right[8];
    float margin_top[8];
    float margin_bottom[8];
    float max_width[8];
    float max_height[8];
    float cross_align[8];
    float avail_width[8];
    float avail_height[8];
    float abs_width[8];
    float abs_height[8];
    float abs_x[8];
    float abs_y[8];
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void wz_layout_chunks(struct WzChunk * chunks, struct WzSlot * slots, int32_t num_chunks);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
