//
// C:\Users\Elior\source\repos\AdventureWizard\Runtime\WzLayout_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
#include <stdbool.h>
//typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_WzChunk__
#define __ISPC_STRUCT_WzChunk__
struct WzChunk {
    float pad_left;
    float pad_right;
    float pad_top;
    float pad_bottom;
    float border_l;
    float border_r;
    float border_t;
    float border_b;
    float child_gap;
    float min_w;
    float min_h;
    float flex_total;
    float inner_w;
    float inner_h;
    float cursor_x;
    float cursor_y;
    int32_t shrink_w;
    int32_t shrink_h;
    uint32_t child_count;
    uint32_t par_chunk;
    uint32_t par_slot;
    int32_t is_horiz;
};
#endif

#ifndef __ISPC_STRUCT_WzSlot__
#define __ISPC_STRUCT_WzSlot__
struct WzSlot {
    float min_w[8];
    float min_h[8];
    float flex[8];
    float margin_l[8];
    float margin_r[8];
    float margin_t[8];
    float margin_b[8];
    float max_w[8];
    float max_h[8];
    float cross_align[8];
    float avail_w[8];
    float avail_h[8];
    float abs_w[8];
    float abs_h[8];
    float abs_x[8];
    float abs_y[8];
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void wz_layout_chunks(struct WzChunk * chunks, struct WzSlot * slots, int32_t num_chunks);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
