// WzLayoutIspc.c
// Shows how to call the ISPC wz_layout function from C.
//
// Build steps:
//   1. ispc WzLayout.ispc -o WzLayout.o --target=avx2-i32x8 --header-outfile=WzLayout_ispc.h
//   2. Compile this file alongside WzLayout.o and link them together.
//
// The generated WzLayout_ispc.h exposes:
//   - struct WzChunk          (plain C struct, matches the ISPC definition)
//   - struct WzSlot_soa<8>    (soa<8> WzSlot becomes a struct with float[8] fields)
//   - void wz_layout(struct WzChunk*, <WzSlot soa type>*, int32_t)

#include "WzLayout_ispc.h"   // auto-generated by ispc --header-outfile
#include <string.h>
#include <assert.h>

#define MAX_CHUNKS  64
#define CHUNK_SIZE   8

// These types come from the generated header.
// soa<8> WzSlot in ISPC becomes a struct where every field is float[8].
// The exact C typedef name is written by ISPC into WzLayout_ispc.h.
// Here we use ispc::WzChunk and ispc::WzSlot as placeholders —
// the real names are whatever the header declares.

void wz_layout_ispc_example(void)
{
    // ---------------------------------------------------------------
    // Allocate.  Both arrays must be 64-byte aligned for AVX2 loads.
    // Use _mm_malloc / _aligned_malloc on Windows, or alignas(64).
    // ---------------------------------------------------------------
    static struct WzChunk chunks[MAX_CHUNKS];

    // soa<8> WzSlot[MAX_CHUNKS * CHUNK_SIZE]:
    // ISPC stores this as MAX_CHUNKS groups of 8 slots each.
    // The generated C type has float[8] for every field of WzSlot,
    // so it is exactly sizeof(float) * 9 fields * 8 slots = 288 bytes per chunk.
    static WzSlot_soa8 slots[MAX_CHUNKS];   // <-- name from WzLayout_ispc.h

    memset(chunks, 0, sizeof(chunks));
    memset(slots,  0, sizeof(slots));

    // ---------------------------------------------------------------
    // Example: two chunks.
    //   chunk 0 = root  (par_chunk 0, par_slot 0 = itself)
    //   chunk 1 = first child group of the root
    // ---------------------------------------------------------------

    // --- chunk 0: root ---
    chunks[0].pad_left   = 5;
    chunks[0].pad_right  = 5;
    chunks[0].pad_top    = 5;
    chunks[0].pad_bottom = 5;
    chunks[0].child_gap  = 4;
    chunks[0].is_horiz   = 0;   // vertical layout
    chunks[0].child_count = 2;
    chunks[0].par_chunk  = 0;   // root is its own parent
    chunks[0].par_slot   = 0;
    chunks[0].cursor_x   = chunks[0].pad_left;
    chunks[0].cursor_y   = chunks[0].pad_top;

    // Root available space = window size (written into slot 0 of chunk 0)
    slots[0].avail_w[0] = 1280;
    slots[0].avail_h[0] = 720;

    // --- chunk 1: two children of the root ---
    chunks[1].pad_left   = 0;
    chunks[1].pad_right  = 0;
    chunks[1].pad_top    = 0;
    chunks[1].pad_bottom = 0;
    chunks[1].child_gap  = 0;
    chunks[1].is_horiz   = 1;   // horizontal layout
    chunks[1].child_count = 2;
    chunks[1].par_chunk  = 0;
    chunks[1].par_slot   = 0;
    chunks[1].cursor_x   = 0;
    chunks[1].cursor_y   = 0;

    // slot 0: fixed-size child, 200 x 50
    slots[1].min_w[0] = 200;
    slots[1].min_h[0] = 50;
    slots[1].flex[0]  = 0;

    // slot 1: flex child, takes remaining width
    slots[1].min_w[1] = 0;
    slots[1].min_h[1] = 50;
    slots[1].flex[1]  = 1;

    // ---------------------------------------------------------------
    // Call the ISPC function.
    // The function pointer name comes from the generated header.
    // ISPC also emits _ispc_dispatch variants for CPU detection.
    // ---------------------------------------------------------------
    wz_layout(chunks, slots, 2 /* num_chunks */);

    // ---------------------------------------------------------------
    // Read results back from slots[chunk].abs_x/y/w/h
    // ---------------------------------------------------------------
    for (int chunk = 0; chunk < 2; ++chunk)
    {
        for (int slot = 0; slot < CHUNK_SIZE; ++slot)
        {
            float w = slots[chunk].abs_w[slot];
            float h = slots[chunk].abs_h[slot];
            if (w == 0 && h == 0) continue;   // unused slot

            float x = slots[chunk].abs_x[slot];
            float y = slots[chunk].abs_y[slot];
            (void)x; (void)y; (void)w; (void)h;
            // hand off to your renderer / WzWidgetData here
        }
    }
}
